INSERT INTO DISEASE VALUES (NEWID(), 'Allergy','Alergia');
INSERT INTO DISEASE VALUES (NEWID(), 'Alzheimer Disease','Mal de Alzheimer');
INSERT INTO DISEASE VALUES (NEWID(), 'Aneurism','Aneurisma');
INSERT INTO DISEASE VALUES (NEWID(), 'Anxiety Disorder','Transtorno de Ansiedade');
INSERT INTO DISEASE VALUES (NEWID(), 'Appendicitis','Apendicite');
INSERT INTO DISEASE VALUES (NEWID(), 'Arthritis','Artrite');
INSERT INTO DISEASE VALUES (NEWID(), 'Asthma','Asma');
INSERT INTO DISEASE VALUES (NEWID(), 'Bronchitis','Bronquite');
INSERT INTO DISEASE VALUES (NEWID(), 'Cancer','Câncer');
INSERT INTO DISEASE VALUES (NEWID(), 'Chicken Pox','Catapora');
INSERT INTO DISEASE VALUES (NEWID(), 'Cholera','Cólera');
INSERT INTO DISEASE VALUES (NEWID(), 'Cirrhosis','Cirrose');
INSERT INTO DISEASE VALUES (NEWID(), 'Cold','Resfriado');
INSERT INTO DISEASE VALUES (NEWID(), 'Conjuctivitis','Conjutivite');
INSERT INTO DISEASE VALUES (NEWID(), 'Depression','Depressão');
INSERT INTO DISEASE VALUES (NEWID(), 'Diabetes','Diabetes');
INSERT INTO DISEASE VALUES (NEWID(), 'Dysentery','Disenteria');
INSERT INTO DISEASE VALUES (NEWID(), 'Encephalitis','Encefalite');
INSERT INTO DISEASE VALUES (NEWID(), 'Flu','Gripe');
INSERT INTO DISEASE VALUES (NEWID(), 'Food poisoning','Intoxicação alimentar');
INSERT INTO DISEASE VALUES (NEWID(), 'Gastritis','Gastrite');
INSERT INTO DISEASE VALUES (NEWID(), 'German Measles','Rubéola');
INSERT INTO DISEASE VALUES (NEWID(), 'Heartburn','Azia');
INSERT INTO DISEASE VALUES (NEWID(), 'Hepatitis','Hepatite');
INSERT INTO DISEASE VALUES (NEWID(), 'High Blood Pressure','Hipertensão, pressão alta');
INSERT INTO DISEASE VALUES (NEWID(), 'Hypochondria','Hipocondria');
INSERT INTO DISEASE VALUES (NEWID(), 'Leukemia','Leucemia');
INSERT INTO DISEASE VALUES (NEWID(), 'Measles','Sarampo');
INSERT INTO DISEASE VALUES (NEWID(), 'Meningitis','Meningite');
INSERT INTO DISEASE VALUES (NEWID(), 'Migraine','Enxaqueca');
INSERT INTO DISEASE VALUES (NEWID(), 'Mumps','Caxumba');
INSERT INTO DISEASE VALUES (NEWID(), 'Obsessive-Compulsive Disorder','Transtorno Obsessivo-Compulsivo');
INSERT INTO DISEASE VALUES (NEWID(), 'Panic Disorder','Síndrome do Pânico');
INSERT INTO DISEASE VALUES (NEWID(), 'Pharyngitis','Faringite');
INSERT INTO DISEASE VALUES (NEWID(), 'Pneumonia','Pneumonia');
INSERT INTO DISEASE VALUES (NEWID(), 'Rabies','Raiva');
INSERT INTO DISEASE VALUES (NEWID(), 'Rheumatism','Reumatismo');
INSERT INTO DISEASE VALUES (NEWID(), 'Rickets','Raquitismo');
INSERT INTO DISEASE VALUES (NEWID(), 'Scarlet fever/Scarlatina','Escarlatina');
INSERT INTO DISEASE VALUES (NEWID(), 'Schizophrenia','Esquizofrenia');
INSERT INTO DISEASE VALUES (NEWID(), 'Smallpox','Varíola');
INSERT INTO DISEASE VALUES (NEWID(), 'Stomach Ache','Dor de barriga/estômago');
INSERT INTO DISEASE VALUES (NEWID(), 'Stroke','Derrame');
INSERT INTO DISEASE VALUES (NEWID(), 'Tetanus','Tétano');
INSERT INTO DISEASE VALUES (NEWID(), 'Trombosis','Trombose');
INSERT INTO DISEASE VALUES (NEWID(), 'Tuberculosis','Tuberculose');
INSERT INTO DISEASE VALUES (NEWID(), 'Typhoid Fever','Febre Tifóide');
INSERT INTO DISEASE VALUES (NEWID(), 'Ulcer','Úlcera');
INSERT INTO DISEASE VALUES (NEWID(), 'Yellow Fever','Febre Amarela');