
CREATE INDEX INDEX_SEARCH
ON HEALTH_INSTITUTION (name, identity_code, country);


DROP INDEX HEALTH_INSTITUTION.INDEX_SEACH;

ALTER TABLE HEALTH_INSTITUTION ALTER COLUMN country VARCHAR(03) NOT NULL;