SELECT * FROM HEALTH_INSTITUTION;



SELECT  *
FROM    ( SELECT    ROW_NUMBER() OVER ( ORDER BY country) AS RowNum, *
          FROM      HEALTH_INSTITUTION WHERE country = 'BR'
        ) AS RowConstrainedResult
WHERE   RowNum >= 1
    AND RowNum < 20
ORDER BY RowNum;

CREATE INDEX INDEX_COORDINATE
ON HEALTH_INSTITUTION (latitute, longitute);


CREATE INDEX INDEX_SEARCH
ON HEALTH_INSTITUTION (name, identity_code, country);


DROP INDEX HEALTH_INSTITUTION.INDEX_SEACH;

ALTER TABLE HEALTH_INSTITUTION ALTER COLUMN country VARCHAR(03) NOT NULL;