
INSERT INTO PHYSICIAN_SPECIALIZATION VALUES (NEWID(), 'Acupuntura','Acupuncture','BRA');
INSERT INTO PHYSICIAN_SPECIALIZATION VALUES (NEWID(), 'Alergia e Imunologia','Allergy and Immunology','BRA');
INSERT INTO PHYSICIAN_SPECIALIZATION VALUES (NEWID(), 'Anestesiologia','Anesthesiologist','BRA');
INSERT INTO PHYSICIAN_SPECIALIZATION VALUES (NEWID(), 'Angiologia','Angiology','BRA');
INSERT INTO PHYSICIAN_SPECIALIZATION VALUES (NEWID(), 'Cancerologia','Cancerology','BRA');
INSERT INTO PHYSICIAN_SPECIALIZATION VALUES (NEWID(), 'Cardiologia','Cardiology','BRA');
INSERT INTO PHYSICIAN_SPECIALIZATION VALUES (NEWID(), 'Cirurgia Cardiovascular','Cardiovascular Surgery','BRA');
INSERT INTO PHYSICIAN_SPECIALIZATION VALUES (NEWID(), 'Cirurgia da Mão','Hand Surgery','BRA');
INSERT INTO PHYSICIAN_SPECIALIZATION VALUES (NEWID(), 'Cirurgia de Cabeça e Pescoço','Head and Neck Surgery','BRA');
INSERT INTO PHYSICIAN_SPECIALIZATION VALUES (NEWID(), 'Cirurgia do Aparelho Digestivo','Digestive Tract Surgery','BRA');
INSERT INTO PHYSICIAN_SPECIALIZATION VALUES (NEWID(), 'Cirurgia Geral','General Surgery','BRA');
INSERT INTO PHYSICIAN_SPECIALIZATION VALUES (NEWID(), 'Cirurgia Pediátrica','Pediatric Surgery','BRA');
INSERT INTO PHYSICIAN_SPECIALIZATION VALUES (NEWID(), 'Cirurgia Plástica','Plastic Surgery','BRA');
INSERT INTO PHYSICIAN_SPECIALIZATION VALUES (NEWID(), 'Cirurgia Torácica','Thoracic Surgery','BRA');
INSERT INTO PHYSICIAN_SPECIALIZATION VALUES (NEWID(), 'Cirurgia Vascular','Vascular Surgery','BRA');
INSERT INTO PHYSICIAN_SPECIALIZATION VALUES (NEWID(), 'Clínica Médica','Medical Clinic','BRA');
INSERT INTO PHYSICIAN_SPECIALIZATION VALUES (NEWID(), 'Coloproctologia','Coloproctology','BRA');
INSERT INTO PHYSICIAN_SPECIALIZATION VALUES (NEWID(), 'Dermatologia','Dermatology','BRA');
INSERT INTO PHYSICIAN_SPECIALIZATION VALUES (NEWID(), 'Endocrinologia e Metabologia','Endocrinology and Metabolism','BRA');
INSERT INTO PHYSICIAN_SPECIALIZATION VALUES (NEWID(), 'Endoscopia','Endoscopy','BRA');
INSERT INTO PHYSICIAN_SPECIALIZATION VALUES (NEWID(), 'Gastroenterologia','Gastroenterology','BRA');
INSERT INTO PHYSICIAN_SPECIALIZATION VALUES (NEWID(), 'Genética Médica','Medical Genetics','BRA');
INSERT INTO PHYSICIAN_SPECIALIZATION VALUES (NEWID(), 'Geriatria','Geriatrics','BRA');
INSERT INTO PHYSICIAN_SPECIALIZATION VALUES (NEWID(), 'Ginecologia e Obstetrícia','Gynecology and Obstetrics','BRA');
INSERT INTO PHYSICIAN_SPECIALIZATION VALUES (NEWID(), 'Hematologia e Hemoterapia','Hematology and Hemotherapy','BRA');
INSERT INTO PHYSICIAN_SPECIALIZATION VALUES (NEWID(), 'Homeopatia','Homeopathy','BRA');
INSERT INTO PHYSICIAN_SPECIALIZATION VALUES (NEWID(), 'Infectologia','Infectology','BRA');
INSERT INTO PHYSICIAN_SPECIALIZATION VALUES (NEWID(), 'Mastologia','Mastology','BRA');
INSERT INTO PHYSICIAN_SPECIALIZATION VALUES (NEWID(), 'Medicina de Família e Comunidade','Family and Community Medicine','BRA');
INSERT INTO PHYSICIAN_SPECIALIZATION VALUES (NEWID(), 'Medicina do Trabalho','Occupational Medicine','BRA');
INSERT INTO PHYSICIAN_SPECIALIZATION VALUES (NEWID(), 'Medicina de Tráfego','Traffic Medicine','BRA');
INSERT INTO PHYSICIAN_SPECIALIZATION VALUES (NEWID(), 'Medicina Esportiva','Sports Medicine','BRA');
INSERT INTO PHYSICIAN_SPECIALIZATION VALUES (NEWID(), 'Medicina Física e Reabilitação','Physical Medicine and Rehabilitation','BRA');
INSERT INTO PHYSICIAN_SPECIALIZATION VALUES (NEWID(), 'Medicina Intensiva','Intensive Medine','BRA');
INSERT INTO PHYSICIAN_SPECIALIZATION VALUES (NEWID(), 'Medicina Legal e Perícia Médica','Legal Medicine and Medical Expertise','BRA');
INSERT INTO PHYSICIAN_SPECIALIZATION VALUES (NEWID(), 'Medicina Nuclear','Nuclear Medicine','BRA');
INSERT INTO PHYSICIAN_SPECIALIZATION VALUES (NEWID(), 'Medicina Preventiva e Social','Preventive and Social Medicine','BRA');
INSERT INTO PHYSICIAN_SPECIALIZATION VALUES (NEWID(), 'Nefrologia','Nephrology','BRA');
INSERT INTO PHYSICIAN_SPECIALIZATION VALUES (NEWID(), 'Neurocirurgia','Neurosurgery','BRA');
INSERT INTO PHYSICIAN_SPECIALIZATION VALUES (NEWID(), 'Neurologia','Neurology','BRA');
INSERT INTO PHYSICIAN_SPECIALIZATION VALUES (NEWID(), 'Nutrologia','Nutrology','BRA');
INSERT INTO PHYSICIAN_SPECIALIZATION VALUES (NEWID(), 'Oftalmologia','Ophthalmology','BRA');
INSERT INTO PHYSICIAN_SPECIALIZATION VALUES (NEWID(), 'Ortopedia e Traumatologia','Orthopedics and Traumatology','BRA');
INSERT INTO PHYSICIAN_SPECIALIZATION VALUES (NEWID(), 'Otorrinolaringologia','Otolaryngology','BRA');
INSERT INTO PHYSICIAN_SPECIALIZATION VALUES (NEWID(), 'Patologia','Pathology','BRA');
INSERT INTO PHYSICIAN_SPECIALIZATION VALUES (NEWID(), 'Patologia Clínica/Medicina Laboratorial','Clinical Pathology/ Laboratory Medicine','BRA');
INSERT INTO PHYSICIAN_SPECIALIZATION VALUES (NEWID(), 'Pediatria','Pediatrics','BRA');
INSERT INTO PHYSICIAN_SPECIALIZATION VALUES (NEWID(), 'Pneumologia','Pneumology','BRA');
INSERT INTO PHYSICIAN_SPECIALIZATION VALUES (NEWID(), 'Psiquiatria','Psychiatry','BRA');
INSERT INTO PHYSICIAN_SPECIALIZATION VALUES (NEWID(), 'Radiologia e Diagnóstico por Imagem','Radiology and Imaging Diagnostics','BRA');
INSERT INTO PHYSICIAN_SPECIALIZATION VALUES (NEWID(), 'Radioterapia','Radiotherapy','BRA');
INSERT INTO PHYSICIAN_SPECIALIZATION VALUES (NEWID(), 'Reumatologia','Rheumatology','BRA');
INSERT INTO PHYSICIAN_SPECIALIZATION VALUES (NEWID(), 'Urologia','Urology','BRA');





INSERT INTO PHYSICIAN_SPECIALIZATION VALUES(NEWID(), 'Psiquiatra de vícios','Addiction Psychiatrist', 'FS');
INSERT INTO PHYSICIAN_SPECIALIZATION VALUES(NEWID(), 'Vícios','Addictions', 'FS');
INSERT INTO PHYSICIAN_SPECIALIZATION VALUES(NEWID(), 'TDAH','ADHD Coaches', 'FS');
INSERT INTO PHYSICIAN_SPECIALIZATION VALUES(NEWID(), 'Aconselhamento Adolescente','Adolescent Counsellors', 'FS');
INSERT INTO PHYSICIAN_SPECIALIZATION VALUES(NEWID(), 'Aconselhamento de adoção','Adoption Counsellors', 'FS');
INSERT INTO PHYSICIAN_SPECIALIZATION VALUES(NEWID(), 'Ginecologia Estética','Aesthetic Gynaecologists', 'FS');
INSERT INTO PHYSICIAN_SPECIALIZATION VALUES(NEWID(), 'Especialista em Medicina Estética','Aesthetic Medicine Specialists', 'FS');
INSERT INTO PHYSICIAN_SPECIALIZATION VALUES(NEWID(), 'Especialista em Gerenciamento de Idade','Age Management Specialists', 'FS');
INSERT INTO PHYSICIAN_SPECIALIZATION VALUES(NEWID(), 'Alergia e Imunologia','Allergist & Immunologists', 'FS');
INSERT INTO PHYSICIAN_SPECIALIZATION VALUES(NEWID(), 'Anestesiologia','Anaesthesiologists', 'FS');
INSERT INTO PHYSICIAN_SPECIALIZATION VALUES(NEWID(), 'Especialista Antienvelhecimento','Anti Aging Specialists', 'FS');
INSERT INTO PHYSICIAN_SPECIALIZATION VALUES(NEWID(), 'Fonoaudiologia','Audiologists', 'FS');
INSERT INTO PHYSICIAN_SPECIALIZATION VALUES(NEWID(), 'Medicina Ayurveda','Ayurveda Physicians', 'FS');
INSERT INTO PHYSICIAN_SPECIALIZATION VALUES(NEWID(), 'Especialista em Medicina Bariárica','Bariatric Medicine Specialists', 'FS');
INSERT INTO PHYSICIAN_SPECIALIZATION VALUES(NEWID(), 'Cirurgião Bariátrico/Metabólico','Bariatric/Metabolic Surgeons', 'FS');
INSERT INTO PHYSICIAN_SPECIALIZATION VALUES(NEWID(), 'Bioquineticista','Biokineticists', 'FS');
INSERT INTO PHYSICIAN_SPECIALIZATION VALUES(NEWID(), 'Eletrofisiologista cardíaco','Cardiac Electrophysiologist', 'FS');
INSERT INTO PHYSICIAN_SPECIALIZATION VALUES(NEWID(), 'Cardiologia','Cardiologists', 'FS');
INSERT INTO PHYSICIAN_SPECIALIZATION VALUES(NEWID(), 'Cirurgia Cardiotorácica','Cardiothoracic Surgeons', 'FS');
INSERT INTO PHYSICIAN_SPECIALIZATION VALUES(NEWID(), 'Educadores Certificados em Diabetes','Certified Diabetes Educators', 'FS');
INSERT INTO PHYSICIAN_SPECIALIZATION VALUES(NEWID(), 'Quiropraxia','Chiropractors', 'FS');
INSERT INTO PHYSICIAN_SPECIALIZATION VALUES(NEWID(), 'Toxicologia de Metal Clínico','Clinical Metal Toxicologists', 'FS');
INSERT INTO PHYSICIAN_SPECIALIZATION VALUES(NEWID(), 'Nutricionista Clínico','Clinical Nutritionists', 'FS');
INSERT INTO PHYSICIAN_SPECIALIZATION VALUES(NEWID(), 'Psicologia Clínica','Clinical Psychologists', 'FS');
INSERT INTO PHYSICIAN_SPECIALIZATION VALUES(NEWID(), 'Clínico','Clinics', 'FS');
INSERT INTO PHYSICIAN_SPECIALIZATION VALUES(NEWID(), 'Cirurgia de Mama Cosmética e Reconstrutiva','Cosmetic and Reconstructive Breast Surgeon', 'FS');
INSERT INTO PHYSICIAN_SPECIALIZATION VALUES(NEWID(), 'Psicologia de Aconselhamento','Counselling Psychologists', 'FS');
INSERT INTO PHYSICIAN_SPECIALIZATION VALUES(NEWID(), 'Especialista em Medicina de Cuidados Intensivos','Critical Care Medicine Specialists', 'FS');
INSERT INTO PHYSICIAN_SPECIALIZATION VALUES(NEWID(), 'Higiene Dental','Dental Hygienists', 'FS');
INSERT INTO PHYSICIAN_SPECIALIZATION VALUES(NEWID(), 'Laboratório Dentário','Dental Laboratories', 'FS');
INSERT INTO PHYSICIAN_SPECIALIZATION VALUES(NEWID(), 'Terapeuta Dentário','Dental Therapists', 'FS');
INSERT INTO PHYSICIAN_SPECIALIZATION VALUES(NEWID(), 'Dentista','Dentists', 'FS');
INSERT INTO PHYSICIAN_SPECIALIZATION VALUES(NEWID(), 'Dermatologia','Dermatologists', 'FS');
INSERT INTO PHYSICIAN_SPECIALIZATION VALUES(NEWID(), 'Diabetologia','Diabetologist', 'FS');
INSERT INTO PHYSICIAN_SPECIALIZATION VALUES(NEWID(), 'Nutricionista','Dieticians', 'FS');
INSERT INTO PHYSICIAN_SPECIALIZATION VALUES(NEWID(), 'Teste de DNA','DNA Tests', 'FS');
INSERT INTO PHYSICIAN_SPECIALIZATION VALUES(NEWID(), 'Cirurgia do Ouvido, Nariz e Garganta/Otorrinolaringologia','Ear, Nose & Throat Surgeon/Otolaryngologists', 'FS');
INSERT INTO PHYSICIAN_SPECIALIZATION VALUES(NEWID(), 'Psicologia Educacional','Educational Psychologists', 'FS');
INSERT INTO PHYSICIAN_SPECIALIZATION VALUES(NEWID(), 'Especialista em Medicina de Emergência','Emergency Medicine Specialists', 'FS');
INSERT INTO PHYSICIAN_SPECIALIZATION VALUES(NEWID(), 'Operações de Emergência','Emergency Operations', 'FS');
INSERT INTO PHYSICIAN_SPECIALIZATION VALUES(NEWID(), 'Endocrinologia','Endocrinologists', 'FS');
INSERT INTO PHYSICIAN_SPECIALIZATION VALUES(NEWID(), 'Endodontia','Endodontists', 'FS');
INSERT INTO PHYSICIAN_SPECIALIZATION VALUES(NEWID(), 'Conselheiro Familiar','Family Counsellors', 'FS');
INSERT INTO PHYSICIAN_SPECIALIZATION VALUES(NEWID(), 'Especialista em Medicina Familiar','Family Medicine Specialists', 'FS');
INSERT INTO PHYSICIAN_SPECIALIZATION VALUES(NEWID(), 'Odontologia Forense','Forensic Odontologists', 'FS');
INSERT INTO PHYSICIAN_SPECIALIZATION VALUES(NEWID(), 'Psicologia Forense','Forensic Psychologists', 'FS');
INSERT INTO PHYSICIAN_SPECIALIZATION VALUES(NEWID(), 'Gastroenterologia','Gastroenterologists', 'FS');
INSERT INTO PHYSICIAN_SPECIALIZATION VALUES(NEWID(), 'Clínico Geral','General Practitioners', 'FS');
INSERT INTO PHYSICIAN_SPECIALIZATION VALUES(NEWID(), 'Cirurgia Geral','General Surgeons', 'FS');
INSERT INTO PHYSICIAN_SPECIALIZATION VALUES(NEWID(), 'Conselheiro Genético','Genetic Counsellors', 'FS');
INSERT INTO PHYSICIAN_SPECIALIZATION VALUES(NEWID(), 'Especialista em Medicina Geriátrica','Geriatric Medicine Specialists', 'FS');
INSERT INTO PHYSICIAN_SPECIALIZATION VALUES(NEWID(), 'Oncologista Ginecológico','Gynaecological Oncologists', 'FS');
INSERT INTO PHYSICIAN_SPECIALIZATION VALUES(NEWID(), 'Ginecologia','Gynaecologists', 'FS');
INSERT INTO PHYSICIAN_SPECIALIZATION VALUES(NEWID(), 'Ginecologia e Obstetrícia','Gynaecologists & Obstetricians', 'FS');
INSERT INTO PHYSICIAN_SPECIALIZATION VALUES(NEWID(), 'Hematologia','Haematologists', 'FS');
INSERT INTO PHYSICIAN_SPECIALIZATION VALUES(NEWID(), 'Cirurgia de Mão','Hand Surgeons', 'FS');
INSERT INTO PHYSICIAN_SPECIALIZATION VALUES(NEWID(), 'Terapeuta da Mão','Hand Therapists', 'FS');
INSERT INTO PHYSICIAN_SPECIALIZATION VALUES(NEWID(), 'Cuidados de Saúde','Health Care', 'FS');
INSERT INTO PHYSICIAN_SPECIALIZATION VALUES(NEWID(), 'Centro de Saúde','Health Centre', 'FS');
INSERT INTO PHYSICIAN_SPECIALIZATION VALUES(NEWID(), 'Saúde e Bem-estar','Health and Wellness Practioners', 'FS');
INSERT INTO PHYSICIAN_SPECIALIZATION VALUES(NEWID(), 'Ajuda de Audição Acústica','Hearing Aid Acousticians', 'FS');
INSERT INTO PHYSICIAN_SPECIALIZATION VALUES(NEWID(), 'Tratamento Holístico','Holistic Treatments', 'FS');
INSERT INTO PHYSICIAN_SPECIALIZATION VALUES(NEWID(), 'Especialista em Saúde Domiciliar','Home Health Care Specialists', 'FS');
INSERT INTO PHYSICIAN_SPECIALIZATION VALUES(NEWID(), 'Homeopatia','Homeopaths', 'FS');
INSERT INTO PHYSICIAN_SPECIALIZATION VALUES(NEWID(), 'Hospitalar','Hospitals', 'FS');
INSERT INTO PHYSICIAN_SPECIALIZATION VALUES(NEWID(), 'Cirurgia Biliar Hepato Pancreático','HPB Hepato-Pancreato-Biliary Surgeons', 'FS');
INSERT INTO PHYSICIAN_SPECIALIZATION VALUES(NEWID(), 'Praticantes de Hipnose','Hypnosis Practitioners', 'FS');
INSERT INTO PHYSICIAN_SPECIALIZATION VALUES(NEWID(), 'Psicologia Industrial','Industrial Psychologists', 'FS');
INSERT INTO PHYSICIAN_SPECIALIZATION VALUES(NEWID(), 'Especialista em Medicina de Doenças Infecciosas','Infectious Disease Medicine Specialists', 'FS');
INSERT INTO PHYSICIAN_SPECIALIZATION VALUES(NEWID(), 'Profissionais de Saúde Integrados','Integrated Health Practitioners', 'FS');
INSERT INTO PHYSICIAN_SPECIALIZATION VALUES(NEWID(), 'Medicina Integrativa','Integrative Medicine', 'FS');
INSERT INTO PHYSICIAN_SPECIALIZATION VALUES(NEWID(), 'Cuidados Intensivos','Intensive Care', 'FS');
INSERT INTO PHYSICIAN_SPECIALIZATION VALUES(NEWID(), 'Especialista em Medicina Interna','Internal Medicine Specialists', 'FS');
INSERT INTO PHYSICIAN_SPECIALIZATION VALUES(NEWID(), 'Cinesioterapia','Kinesiotherapists', 'FS');
INSERT INTO PHYSICIAN_SPECIALIZATION VALUES(NEWID(), 'Cirurgia Laparoscópica','Laproscopic Surgeons', 'FS');
INSERT INTO PHYSICIAN_SPECIALIZATION VALUES(NEWID(), 'Cirugia Bucomaxilofacial','Maxillofacial & Oral Surgeons', 'FS');
INSERT INTO PHYSICIAN_SPECIALIZATION VALUES(NEWID(), 'Administradores de Contas Médicas','Medical Accounts Administrators', 'FS');
INSERT INTO PHYSICIAN_SPECIALIZATION VALUES(NEWID(), 'Consultaoria Médica','Medical Consultants', 'FS');
INSERT INTO PHYSICIAN_SPECIALIZATION VALUES(NEWID(), 'Genética Médica','Medical Genetics', 'FS');
INSERT INTO PHYSICIAN_SPECIALIZATION VALUES(NEWID(), 'Seguro Médico','Medical Insurance', 'FS');
INSERT INTO PHYSICIAN_SPECIALIZATION VALUES(NEWID(), 'Oncologia Médica','Medical Oncologists', 'FS');
INSERT INTO PHYSICIAN_SPECIALIZATION VALUES(NEWID(), 'Serviço de Prática Médica','Medical Practice Services', 'FS');
INSERT INTO PHYSICIAN_SPECIALIZATION VALUES(NEWID(), 'Turismo Médico','Medical Tourism', 'FS');
INSERT INTO PHYSICIAN_SPECIALIZATION VALUES(NEWID(), 'Especialista em Medicina Metabólica','Metabolic Medicine Specialists', 'FS');
INSERT INTO PHYSICIAN_SPECIALIZATION VALUES(NEWID(), 'Parteira','Midwives', 'FS');
INSERT INTO PHYSICIAN_SPECIALIZATION VALUES(NEWID(), 'Atenção Plena Baseada em Intervenções e Abordagens','Mindfulness Based Interventions and Approaches', 'FS');
INSERT INTO PHYSICIAN_SPECIALIZATION VALUES(NEWID(), 'Naprapath','Naprapath', 'FS');
INSERT INTO PHYSICIAN_SPECIALIZATION VALUES(NEWID(), 'Naturopatas','Naturopaths', 'FS');
INSERT INTO PHYSICIAN_SPECIALIZATION VALUES(NEWID(), 'Neurologia','Neurologists', 'FS');
INSERT INTO PHYSICIAN_SPECIALIZATION VALUES(NEWID(), 'Neuromusculoesquelético','Neuromusculoskeletal Medicine', 'FS');
INSERT INTO PHYSICIAN_SPECIALIZATION VALUES(NEWID(), 'Neuropsicologia','Neuropsychologists', 'FS');
INSERT INTO PHYSICIAN_SPECIALIZATION VALUES(NEWID(), 'Neurocirurgia','Neurosurgeons', 'FS');
INSERT INTO PHYSICIAN_SPECIALIZATION VALUES(NEWID(), 'Especialista em Medicina Nuclear','Nuclear Medicine Specialists', 'FS');
INSERT INTO PHYSICIAN_SPECIALIZATION VALUES(NEWID(), 'Especialista em Saúde Ocupacional','Occupational Health Specialists', 'FS');
INSERT INTO PHYSICIAN_SPECIALIZATION VALUES(NEWID(), 'Especialista em Medicina Ocupacional','Occupational Medicine Specialist', 'FS');
INSERT INTO PHYSICIAN_SPECIALIZATION VALUES(NEWID(), 'Terapia Ocupacional','Occupational Therapists', 'FS');
INSERT INTO PHYSICIAN_SPECIALIZATION VALUES(NEWID(), 'Oncologia','Oncologists', 'FS');
INSERT INTO PHYSICIAN_SPECIALIZATION VALUES(NEWID(), 'Oftalmologia','Ophthalmologists', 'FS');
INSERT INTO PHYSICIAN_SPECIALIZATION VALUES(NEWID(), 'Optometrista','Optometrists', 'FS');
INSERT INTO PHYSICIAN_SPECIALIZATION VALUES(NEWID(), 'Ortodontista','Orthodontists', 'FS');
INSERT INTO PHYSICIAN_SPECIALIZATION VALUES(NEWID(), 'Cirurgia Ortopédica','Orthopaedic Surgeons', 'FS');
INSERT INTO PHYSICIAN_SPECIALIZATION VALUES(NEWID(), 'Órteses e Especialistas em Próteses','Orthotics & Prosthetic Specialists', 'FS');
INSERT INTO PHYSICIAN_SPECIALIZATION VALUES(NEWID(), 'Osteopatas','Osteopaths', 'FS');
INSERT INTO PHYSICIAN_SPECIALIZATION VALUES(NEWID(), 'Alergologista Pediátrico','Paediatric Allergists', 'FS');
INSERT INTO PHYSICIAN_SPECIALIZATION VALUES(NEWID(), 'Dentista Pediátrico','Paediatric Dentists', 'FS');
INSERT INTO PHYSICIAN_SPECIALIZATION VALUES(NEWID(), 'Cardiologista Pediátrico','Paediatric Cardiologists', 'FS');
INSERT INTO PHYSICIAN_SPECIALIZATION VALUES(NEWID(), 'Endocrinologista Pediátrico','Paediatric Endocrinologist', 'FS');
INSERT INTO PHYSICIAN_SPECIALIZATION VALUES(NEWID(), 'Gastroenterologista Pediátrico','Paediatric Gastroenterologists', 'FS');
INSERT INTO PHYSICIAN_SPECIALIZATION VALUES(NEWID(), 'Neurologista Pediátrico','Paediatric Neurologists', 'FS');
INSERT INTO PHYSICIAN_SPECIALIZATION VALUES(NEWID(), 'Pneumonologista Pediátrico','Paediatric Pulmonologist', 'FS');
INSERT INTO PHYSICIAN_SPECIALIZATION VALUES(NEWID(), 'Cirurgião Pediátrico','Paediatric Surgeons', 'FS');
INSERT INTO PHYSICIAN_SPECIALIZATION VALUES(NEWID(), 'Pediatra','Paediatricians', 'FS');
INSERT INTO PHYSICIAN_SPECIALIZATION VALUES(NEWID(), 'Especialista em Medicina da Dor','Pain Medicine Specialists', 'FS');
INSERT INTO PHYSICIAN_SPECIALIZATION VALUES(NEWID(), 'Patologista','Pathologists', 'FS');
INSERT INTO PHYSICIAN_SPECIALIZATION VALUES(NEWID(), 'Periodontitas','Periodontists', 'FS');
INSERT INTO PHYSICIAN_SPECIALIZATION VALUES(NEWID(), 'Personal Trainers','Personal Trainers', 'FS');
INSERT INTO PHYSICIAN_SPECIALIZATION VALUES(NEWID(), 'Farmácia','Pharmacist', 'FS');
INSERT INTO PHYSICIAN_SPECIALIZATION VALUES(NEWID(), 'Reabilitação física','Physical Rehabilitation', 'FS');
INSERT INTO PHYSICIAN_SPECIALIZATION VALUES(NEWID(), 'Fisioterapeuta','Physiotherapists', 'FS');
INSERT INTO PHYSICIAN_SPECIALIZATION VALUES(NEWID(), 'Pilates','Pilates', 'FS');
INSERT INTO PHYSICIAN_SPECIALIZATION VALUES(NEWID(), 'Cirurgião Plástico e de Reconstrução','Plastic & Reconstructive Surgeons', 'FS');
INSERT INTO PHYSICIAN_SPECIALIZATION VALUES(NEWID(), 'Podólogo','Podiatrists', 'FS');
INSERT INTO PHYSICIAN_SPECIALIZATION VALUES(NEWID(), 'Especialista em Medicina preventiva','Preventive Medicine Specialists', 'FS');
INSERT INTO PHYSICIAN_SPECIALIZATION VALUES(NEWID(), 'Restauração e substituição de dentes','Prosthodontists', 'FS');
INSERT INTO PHYSICIAN_SPECIALIZATION VALUES(NEWID(), 'Psiquiatra','Psychiatrists', 'FS');
INSERT INTO PHYSICIAN_SPECIALIZATION VALUES(NEWID(), 'Psicometrista','Psychometrists', 'FS');
INSERT INTO PHYSICIAN_SPECIALIZATION VALUES(NEWID(), 'Psychotherapia','Psychotherapists', 'FS');
INSERT INTO PHYSICIAN_SPECIALIZATION VALUES(NEWID(), 'Pulmonologista','Pulmonologists', 'FS');
INSERT INTO PHYSICIAN_SPECIALIZATION VALUES(NEWID(), 'Oncologista de Radiação','Radiation Oncologists', 'FS');
INSERT INTO PHYSICIAN_SPECIALIZATION VALUES(NEWID(), 'Radiologista','Radiologists', 'FS');
INSERT INTO PHYSICIAN_SPECIALIZATION VALUES(NEWID(), 'Conselheiros Registrados','Registered Counsellors', 'FS');
INSERT INTO PHYSICIAN_SPECIALIZATION VALUES(NEWID(), 'Radiografistas Registrados','Registered Radiographers', 'FS');
INSERT INTO PHYSICIAN_SPECIALIZATION VALUES(NEWID(), 'Centro de Reabilitação Registrado','Registered Rehabilitation Centre', 'FS');
INSERT INTO PHYSICIAN_SPECIALIZATION VALUES(NEWID(), 'Especialista em Medicina Reprodutiva','Reproductive Medicine Specialists', 'FS');
INSERT INTO PHYSICIAN_SPECIALIZATION VALUES(NEWID(), 'Reumatologista','Rheumatologists', 'FS');
INSERT INTO PHYSICIAN_SPECIALIZATION VALUES(NEWID(), 'Cirurgião de Rinoplastia','Rhinoplasty Surgeons', 'FS');
INSERT INTO PHYSICIAN_SPECIALIZATION VALUES(NEWID(), 'Cirurgião Robótico','Robotic Surgeons', 'FS');
INSERT INTO PHYSICIAN_SPECIALIZATION VALUES(NEWID(), 'Sexologista','Sexologists', 'FS');
INSERT INTO PHYSICIAN_SPECIALIZATION VALUES(NEWID(), 'Medicina Sexual','Sexual Medicine', 'FS');
INSERT INTO PHYSICIAN_SPECIALIZATION VALUES(NEWID(), 'Especialista em Disordem do Sono','Sleep Disorder Specialists', 'FS');
INSERT INTO PHYSICIAN_SPECIALIZATION VALUES(NEWID(), 'Responsabilidade Social','Social Responsibility', 'FS');
INSERT INTO PHYSICIAN_SPECIALIZATION VALUES(NEWID(), 'Trabalhadores Sociais','Social Workers', 'FS');
INSERT INTO PHYSICIAN_SPECIALIZATION VALUES(NEWID(), 'Cirurgião Especialista','Specialist Surgeons', 'FS');
INSERT INTO PHYSICIAN_SPECIALIZATION VALUES(NEWID(), 'Terapeutas da Fala','Speech Therapists', 'FS');
INSERT INTO PHYSICIAN_SPECIALIZATION VALUES(NEWID(), 'Especialista em Medicina do Esporte','Sports Medicine Specialists', 'FS');
INSERT INTO PHYSICIAN_SPECIALIZATION VALUES(NEWID(), 'Terapeuta','Therapists', 'FS');
INSERT INTO PHYSICIAN_SPECIALIZATION VALUES(NEWID(), 'Conselheiro de Trauma','Trauma Counsellors', 'FS');
INSERT INTO PHYSICIAN_SPECIALIZATION VALUES(NEWID(), 'Urologista','Urologists', 'FS');
INSERT INTO PHYSICIAN_SPECIALIZATION VALUES(NEWID(), 'Cirurgião Vascular','Vascular Surgeons', 'FS');
INSERT INTO PHYSICIAN_SPECIALIZATION VALUES(NEWID(), 'Especialista em Saúde da Mulher','Womens Health Specialists', 'FS');



INSERT INTO NURSE_SPECIALIZATION VALUES (NEWID(), 'Aeroespacial','Aerospace','BRA');
INSERT INTO NURSE_SPECIALIZATION VALUES (NEWID(), 'Assistência ao Adolescente','Adolescent Care','BRA');
INSERT INTO NURSE_SPECIALIZATION VALUES (NEWID(), 'Atendimento Pré-Hospitalar','Prehospital Care','BRA');
INSERT INTO NURSE_SPECIALIZATION VALUES (NEWID(), 'Banco de Leite Humano','Milk Bank','BRA');
INSERT INTO NURSE_SPECIALIZATION VALUES (NEWID(), 'Cardiovascular','Cardiovascular','BRA');
INSERT INTO NURSE_SPECIALIZATION VALUES (NEWID(), 'Central de Material e Esterilização','Material and Sterilization Center','BRA');
INSERT INTO NURSE_SPECIALIZATION VALUES (NEWID(), 'Centro Cirúrgico','Surgery Center','BRA');
INSERT INTO NURSE_SPECIALIZATION VALUES (NEWID(), 'Clínica Cirúrgica','Surgical Clinic','BRA');
INSERT INTO NURSE_SPECIALIZATION VALUES (NEWID(), 'Clínica Médica','Medical Clinic','BRA');
INSERT INTO NURSE_SPECIALIZATION VALUES (NEWID(), 'Dermatologia','Dermatology','BRA');
INSERT INTO NURSE_SPECIALIZATION VALUES (NEWID(), 'Diagnóstico por Imagem','Diagnostic by Image','BRA');
INSERT INTO NURSE_SPECIALIZATION VALUES (NEWID(), 'Doenças Infecciosas','Infectious Diseases','BRA');
INSERT INTO NURSE_SPECIALIZATION VALUES (NEWID(), 'Educação em Enfermagem','Education in Nursing','BRA');
INSERT INTO NURSE_SPECIALIZATION VALUES (NEWID(), 'Emergência','Emergency','BRA');
INSERT INTO NURSE_SPECIALIZATION VALUES (NEWID(), 'Endocrinologia','Endocrinology','BRA');
INSERT INTO NURSE_SPECIALIZATION VALUES (NEWID(), 'Endoscopia','Endoscopy','BRA');
INSERT INTO NURSE_SPECIALIZATION VALUES (NEWID(), 'Estomaterapia','Stomatherapy','BRA');
INSERT INTO NURSE_SPECIALIZATION VALUES (NEWID(), 'Ética e Bioética','Ethics and Bioethics','BRA');
INSERT INTO NURSE_SPECIALIZATION VALUES (NEWID(), 'Gerenciamento de Serviços de Saúde','Health Service Management','BRA');
INSERT INTO NURSE_SPECIALIZATION VALUES (NEWID(), 'Gerontologia e Geriatria','Gerontology and Geriatrics','BRA');
INSERT INTO NURSE_SPECIALIZATION VALUES (NEWID(), 'Ginecologia','Gerontology','BRA');
INSERT INTO NURSE_SPECIALIZATION VALUES (NEWID(), 'Hemo dinâmica','Hemodynamics','BRA');
INSERT INTO NURSE_SPECIALIZATION VALUES (NEWID(), 'Homecare','Homecare','BRA');
INSERT INTO NURSE_SPECIALIZATION VALUES (NEWID(), 'Infecção Hospitalar','Hospital Infection','BRA');
INSERT INTO NURSE_SPECIALIZATION VALUES (NEWID(), 'Informática','Computing','BRA');
INSERT INTO NURSE_SPECIALIZATION VALUES (NEWID(), 'Nefrologia','Nefrology','BRA');
INSERT INTO NURSE_SPECIALIZATION VALUES (NEWID(), 'Neonatologia','Neonatology','BRA');
INSERT INTO NURSE_SPECIALIZATION VALUES (NEWID(), 'Nutrição Parenteral','Parental Nutrition','BRA');
INSERT INTO NURSE_SPECIALIZATION VALUES (NEWID(), 'Obstetrícia','Obstetrics','BRA');
INSERT INTO NURSE_SPECIALIZATION VALUES (NEWID(), 'Oftalmologia','Ophthalmology','BRA');
INSERT INTO NURSE_SPECIALIZATION VALUES (NEWID(), 'Oncologia','Oncology','BRA');
INSERT INTO NURSE_SPECIALIZATION VALUES (NEWID(), 'Otorrinolaringologia','Otolaryngology','BRA');
INSERT INTO NURSE_SPECIALIZATION VALUES (NEWID(), 'Pediatria','Pediatrics','BRA');
INSERT INTO NURSE_SPECIALIZATION VALUES (NEWID(), 'Perícia e Auditoria','Expertise and Audit','BRA');
INSERT INTO NURSE_SPECIALIZATION VALUES (NEWID(), 'Psiquiatria e Saúde Mental','Psychiatry and Menthal Health','BRA');
INSERT INTO NURSE_SPECIALIZATION VALUES (NEWID(), 'Saúde Coletiva','Collective Healh','BRA');
INSERT INTO NURSE_SPECIALIZATION VALUES (NEWID(), 'Saúde da Família','Family Health','BRA');
INSERT INTO NURSE_SPECIALIZATION VALUES (NEWID(), 'Sexologia Humana','Human Sexology','BRA');
INSERT INTO NURSE_SPECIALIZATION VALUES (NEWID(), 'Trabalho','Work','BRA');
INSERT INTO NURSE_SPECIALIZATION VALUES (NEWID(), 'Traumato-Ortopedia','Traumato-orthopedics','BRA');
INSERT INTO NURSE_SPECIALIZATION VALUES (NEWID(), 'Terapia Intensiva','Intensive Therapy','BRA');
INSERT INTO NURSE_SPECIALIZATION VALUES (NEWID(), 'Terapias Naturais/Tradicionais e Complementares/Não Convencionais','Natural / traditional and complementary / non-conventional therapies','BRA');


INSERT INTO NURSE_SPECIALIZATION VALUES (NEWID(), 'Atenção Primária a Saúde','Primary health care', 'FS');
INSERT INTO NURSE_SPECIALIZATION VALUES (NEWID(), 'Gerenciamento','Management', 'FS');
INSERT INTO NURSE_SPECIALIZATION VALUES (NEWID(), 'Ocupacional','Occupational', 'FS');
INSERT INTO NURSE_SPECIALIZATION VALUES (NEWID(), 'Saúde Ortopédica','Health Orthopaedic', 'FS');
INSERT INTO NURSE_SPECIALIZATION VALUES (NEWID(), 'Unidade de Cuidados Intensivos','ICU', 'FS');
INSERT INTO NURSE_SPECIALIZATION VALUES (NEWID(), 'Vigilância de Doença Realizada Avançada Pediátrica de Trauma','Trauma Paeds', 'FS');
INSERT INTO NURSE_SPECIALIZATION VALUES (NEWID(), 'Obstetrícia Avançada','Advanced Midwifery', 'FS');
INSERT INTO NURSE_SPECIALIZATION VALUES (NEWID(), 'Oftalmologia','Opthalmology', 'FS');
INSERT INTO NURSE_SPECIALIZATION VALUES (NEWID(), 'Tecnologia de Teatro','Theatre tech', 'FS');
INSERT INTO NURSE_SPECIALIZATION VALUES (NEWID(), 'Cuidados Intensivos','Intensive care', 'FS');
INSERT INTO NURSE_SPECIALIZATION VALUES (NEWID(), 'Pediatria','Pediatrics', 'FS');
INSERT INTO NURSE_SPECIALIZATION VALUES (NEWID(), 'Ortopedia','Orthopedics', 'FS');
