CREATE TABLE USER_HEALTH(
	id_user CHAR(36) PRIMARY KEY,
	login VARCHAR(100) NOT NULL,
	password CHAR(64) NOT NULL,
	name VARCHAR(100),
	type_of_user VARCHAR(02) NOT NULL,
	born_date DATE,
	gender CHAR(01),
	postal_code CHAR(08),
	country VARCHAR(03) NOT NULL,
	state VARCHAR(100),
	city VARCHAR(100),
	street VARCHAR(100),
	neighborhood VARCHAR(50),
	number VARCHAR(10),
	photo VARCHAR(100),
	identity_document VARCHAR(20),
	telephone VARCHAR(20),
	secret_code VARCHAR(04) NOT NULL
);

delete from user_health where id_user = 'b691ad67-98ae-44a6-ac9a-f5c56b2f7f0b'

select * from USER_HEALTH;
ALTER TABLE USER_HEALTH ALTER COLUMN secret_code VARCHAR(04) NOT NULL;

ALTER TABLE dbo.USER_HEALTH ALTER COLUMN country varchar(03) not null;

ALTER TABLE dbo.USER_HEALTH
  ADD CONSTRAINT UK_SECRET_CODE UNIQUE (secret_code)

ALTER TABLE dbo.USER_HEALTH
  ADD CONSTRAINT UK_USER UNIQUE (login, identity_document, country, type_of_user)
  
  DELETE FROM USER_HEALTH;

  SELECT * FROM USER_HEALTH;

CREATE TABLE HEALTH_INSTITUTION(
	id_health_institution CHAR(36) PRIMARY KEY,
	identity_code VARCHAR(20) NOT NULL,
	name VARCHAR(100) NOT NULL,
	postal_code CHAR(08),
	country CHAR(02) NOT NULL,
	state VARCHAR(100) NOT NULL,
	city VARCHAR(100) NOT NULL,
	street VARCHAR(100) NOT NULL,
	neighborhood VARCHAR(50) NOT NULL,
	number VARCHAR(10) NOT NULL,
	photo VARCHAR(100),
	latitute FLOAT NOT NULL,
	longitute FLOAT NOT NULL
);


CREATE TABLE USER_AND_HEALTH_INSTITUTION(
	id_user_works_in_health_institution CHAR(36) PRIMARY KEY,
	id_user CHAR(36) NOT NULL  FOREIGN KEY REFERENCES USER_HEALTH(id_user) ON DELETE CASCADE,
	id_health_institution CHAR(36) NOT NULL FOREIGN KEY REFERENCES HEALTH_INSTITUTION(id_health_institution) ON DELETE CASCADE,
	status char(01) NOT NULL
);


CREATE TABLE PHYSICIAN(
	id_physician CHAR(36) PRIMARY KEY,
	id_user CHAR(36) NOT NULL  FOREIGN KEY REFERENCES USER_HEALTH(id_user) ON DELETE CASCADE,
	practice_document VARCHAR(20) NOT NULL
);



CREATE TABLE PHYSICIAN_SPECIALIZATION(
	id_specialization CHAR(36) PRIMARY KEY,
	name_pt VARCHAR(100) NOT NULL,
	name_en VARCHAR(100) NOT NULL,
	country VARCHAR(03) NOT NULL
);
drop table PHYSICIAN_SPECIALIZATION;


CREATE TABLE PHYSICIAN_HAS_SPECIALIZATION(
	id_physician_has_specialization CHAR(36) PRIMARY KEY,
	id_physician CHAR(36) NOT NULL FOREIGN KEY REFERENCES PHYSICIAN(id_physician) ON DELETE CASCADE,
	id_specialization CHAR(36) NOT NULL FOREIGN KEY REFERENCES PHYSICIAN_SPECIALIZATION(id_specialization) ON DELETE CASCADE
);

drop table physician_has_specialization;


CREATE TABLE NURSE(
	id_nurse CHAR(36) PRIMARY KEY,
	id_user CHAR(36) NOT NULL  FOREIGN KEY REFERENCES USER_HEALTH(id_user) ON DELETE CASCADE,
	nurse_code VARCHAR(15) NOT NULL,
	nurse_type VARCHAR(02) NOT NULL,

);

ALTER TABLE NURSE ADD CONSTRAINT UK_NURSE UNIQUE (id_user)


CREATE TABLE NURSE_SPECIALIZATION(
	id_specialization CHAR(36) PRIMARY KEY,
	name_pt VARCHAR(100) NOT NULL,
	name_en VARCHAR(100) NOT NULL,
	country VARCHAR(03) NOT NULL

);



CREATE TABLE NURSE_HAS_SPECIALIZATION(
	id_nurse_has_specialization CHAR(36) PRIMARY KEY,
	id_nurse CHAR(36) NOT NULL FOREIGN KEY REFERENCES NURSE(id_nurse) ON DELETE CASCADE,
	id_specialization CHAR(36) NOT NULL FOREIGN KEY REFERENCES NURSE_SPECIALIZATION(id_specialization) ON DELETE CASCADE
);





select * from USER_HEALTH;

CREATE TABLE PATIENT(
	id_patient CHAR(36) PRIMARY KEY,
	blood_type VARCHAR(02),
	color VARCHAR(02),
	father_name VARCHAR(100),
	mother_name VARCHAR(100),
	weight FLOAT,
	height float,
	id_user CHAR(36) NOT NULL  FOREIGN KEY REFERENCES USER_HEALTH(id_user) ON DELETE CASCADE,
	status CHAR(01)

);

ALTER TABLE PATIENT ADD CONSTRAINT UK_PATIENT UNIQUE (id_user)


INSERT INTO PATIENT VALUES(NEWID(), '0', '1', 'Salvador Gutierrez Gonçales', 'Silvana Aparecida Lacava', 0, 0, 'd4a26958-d04a-45f2-a04a-11d9d6590c6d', 0);





SELECT * FROM PATIENT;


select * from user_health;

select * from patient;
/**


blood type
0 not selected
1  a+
2  b+ 
3  ab +
4  o +
5  a - 
6  b - 
7  ab -
8  o - 
*/


/**
color
Fitzpatrick type	von Luschan scale	Also called
0 - not selected
1-------	0–6	Very light or white, "Celtic" type[4]
2-------	7–13	Light or light-skinned European[4]
3-------	14–20	Light intermediate, or dark-skinned European[4]
4-------	21–27	Dark intepatientrmediate or "olive skin"[4]
5-------	28–34	Dark or "brown" type
6-------	35–36	Very dark or "black" type

*/



/**

status
0 - não verificado
1 - verificado

*/

ALTER TABLE PATIENT
ADD status CHAR(01);


CREATE TABLE PATIENT_HAS_TAG(
	id_patient_has_tag CHAR(36) PRIMARY KEY,
	mac_code VARCHAR(36) UNIQUE,
	id_patient CHAR(36) NOT NULL,
	tag_type VARCHAR(02),
	name VARCHAR(100),
	CONSTRAINT FK_PATIENT_HAS_TAG FOREIGN KEY (id_patient) REFERENCES PATIENT(id_patient) ON DELETE CASCADE


);

ALTER TABLE PATIENT_HAS_TAG
ADD tag_type VARCHAR(02);


ALTER TABLE PATIENT_HAS_TAG
ADD name VARCHAR(100);


select * from user_health where id_user = '90a35581-ff61-4028-bd1b-a5c0dea71c83';

INSERT INTO PATIENT_HAS_TAG VALUES('51A88082-0051-4272-B75F-1B742BE77ADB', '0xA6-0x9D-0xB8-0x1F', 'F8313B58-F807-4098-A74B-64BF456FA838');
INSERT INTO PATIENT_HAS_TAG VALUES('78ff7fac-0526-483a-9ce3-683220ac2158', '0xF6-0x34-0x88-0xA1', '90a35581-ff61-4028-bd1b-a5c0dea71c83');

SELECT * FROM PATIENT_HAS_TAG WHERE id_patient = '90a35581-ff61-4028-bd1b-a5c0dea71c83';
SELECT * FROM PATIENT_HAs_TAG;


ALTER TABLE PATIENT_HAS_TAG
ADD CONSTRAINT PK_PATIENT_HAS_TAG;


insert into PATIENT_HAS_TAG values(NEWID(), '0xA6-0x9D-0xB8-0x1F', 'F8313B58-F807-4098-A74B-64BF456FA838');
SELECT PATIENT.blood_type, PATIENT.color,  PATIENT.father_name, PATIENT.mother_name, 
				PATIENT.height, PATIENT.weight, PATIENT.id_user,  PATIENT.id_patient, 
				 PATIENT.status FROM PATIENT_HAS_TAG INNER JOIN  
				 PATIENT ON  PATIENT.id_patient = PATIENT_HAS_TAG.id_patient 
				 WHERE PATIENT_HAS_TAG.mac_code = '0xA6-0x9D-0xB8-0x1F'

select * from patient;

select * from PATIENT_HAS_TAG;


SELECT * FROM patient_has_tag;

insert into patient_has_tag values(newid(), '45454545454', '400973e0-a178-4fcb-ba26-48839018d601');
insert into patient_has_tag values(newid(), '2222222222222', '400973e0-a178-4fcb-ba26-48839018d601');



SELECT PATIENT.blood_type, PATIENT.color, 
PATIENT.father_name,
PATIENT.mother_name,
PATIENT.height,
PATIENT.weight,
PATIENT.id_user,
PATIENT.id_patient,
PATIENT.status FROM PATIENT_HAS_TAG INNER JOIN 
PATIENT ON  PATIENT.id_patient = PATIENT_HAS_TAG.id_patient
where PATIENT_HAS_TAG.mac_code = '45454545454';


CREATE TABLE PATIENT_DID_SURGERY(
	id_patient_did_surgery CHAR(36) PRIMARY KEY,
	title VARCHAR(100) NOT NULL,
	time TIME,
	date DATE,
	status CHAR(01) NOT NULL,
	anotations TEXT,
	id_patient CHAR(36) NOT NULL  FOREIGN KEY REFERENCES PATIENT(id_patient) ON DELETE CASCADE,

);



CREATE TABLE DIAGNOSIS(
	id_diagnosis CHAR(36) PRIMARY KEY,
	date_diagnosis datetime NOT NULL DEFAULT current_timestamp,
	anotation TEXT,
	id_patient CHAR(36) NOT NULL  CONSTRAINT FK_diagnosis_patient FOREIGN KEY REFERENCES PATIENT(id_patient),
	id_physician CHAR(36) NOT NULL  CONSTRAINT FK_diagnosis_physician  FOREIGN KEY REFERENCES PHYSICIAN(id_physician),
	id_health_institution CHAR(36) NOT NULL CONSTRAINT FK_diagnosis_health_institution FOREIGN KEY REFERENCES HEALTH_INSTITUTION(id_health_institution)

);




CREATE TABLE DISEASE(
	id_disease CHAR(36) PRIMARY KEY,
	name_en VARCHAR(100) NOT NULL,
	name_pt VARCHAR(100) NOT NULL,
);


drop table disease;


drop table disease;
drop table PATIENT_HAS_DISEASE;


CREATE TABLE PATIENT_HAS_DISEASE(
	id_patient_has_disease CHAR(36) PRIMARY KEY,
	id_patient CHAR(36) NOT NULL  FOREIGN KEY REFERENCES PATIENT(id_patient) ON DELETE CASCADE,
	id_disease CHAR(36) NOT NULL  FOREIGN KEY REFERENCES DISEASE(id_disease) ON DELETE CASCADE,
	anotations TEXT
);




CREATE TABLE EXAM(
	id_exam CHAR(36) PRIMARY KEY,
	date_exam datetime NOT NULL DEFAULT current_timestamp,
	anotation TEXT,
	id_patient CHAR(36) NOT NULL  CONSTRAINT FK_exam_patient FOREIGN KEY REFERENCES PATIENT(id_patient),
	id_physician CHAR(36) NOT NULL  CONSTRAINT FK_exam_physician  FOREIGN KEY REFERENCES PHYSICIAN(id_physician),
	id_health_institution CHAR(36) NOT NULL CONSTRAINT FK_exam_health_institution FOREIGN KEY REFERENCES HEALTH_INSTITUTION(id_health_institution)
);



CREATE TABLE EXAM_ATTACHMENT(
	id_exam_attachment CHAR(36) PRIMARY KEY,
	attachment_name VARCHAR(100),
	id_exam CHAR(36) NOT NULL  CONSTRAINT FK_exam_attachment_exam FOREIGN KEY REFERENCES EXAM(id_exam) ON DELETE CASCADE
);

drop table EXAM_ATTACHMENT;







CREATE TABLE FAMILY_MEMBER(
	id_family_member CHAR(36) PRIMARY KEY,
	name VARCHAR(100) NOT NULL,
	id_patient CHAR(36) NOT NULL  FOREIGN KEY REFERENCES PATIENT(id_patient) ON DELETE CASCADE,

);


drop table FAMILY_MEMBER_HAS_DISEASE;

CREATE TABLE FAMILY_MEMBER_HAS_DISEASE(
	id_family_member_has_disease CHAR(36) PRIMARY KEY,
	id_disease CHAR(36) NOT NULL  FOREIGN KEY REFERENCES DISEASE(id_disease) ON DELETE CASCADE,
	id_family_member CHAR(36) NOT NULL  FOREIGN KEY REFERENCES FAMILY_MEMBER(id_family_member) ON DELETE CASCADE,

);




CREATE TABLE DEFICIENCY(
	id_deficiency CHAR(36) PRIMARY KEY,
	name_en VARCHAR(100) NOT NULL,
	name_pt VARCHAR(100) NOT NULL
);

drop table deficiency;
CREATE TABLE PATIENT_HAS_DEFICIENCY(
	id_patient_has_deficiency CHAR(36) PRIMARY KEY,
	id_patient CHAR(36) NOT NULL  FOREIGN KEY REFERENCES PATIENT(id_patient) ON DELETE CASCADE,
	id_deficiency CHAR(36) NOT NULL  FOREIGN KEY REFERENCES DEFICIENCY(id_deficiency) ON DELETE CASCADE,
	anotation TEXT
);


CREATE TABLE MEDICATION(
	id_medication CHAR(36) PRIMARY KEY,
	name VARCHAR(100) NOT NULL,
	description TEXT,
	country VARCHAR(03) NOT NULL
);

drop table medication;


CREATE TABLE PATIENT_USE_MEDICATION(
	id_patient_use_medication CHAR(36) PRIMARY KEY,
	id_patient CHAR(36) NOT NULL  FOREIGN KEY REFERENCES PATIENT(id_patient) ON DELETE CASCADE,
	id_medication CHAR(36) NOT NULL  FOREIGN KEY REFERENCES MEDICATION(id_medication) ON DELETE CASCADE,
	anotations TEXT
);


drop table PATIENT_USE_MEDICATION;































SELECT  
PHYSICIAN_HAS_SPECIALIZATION.id_specialization 
FROM PHYSICIAN_HAS_SPECIALIZATION
 INNER JOIN PHYSICIAN ON PHYSICIAN.id_physician =  PHYSICIAN_HAS_SPECIALIZATION.id_physician 
 INNER JOIN PHYSICIAN_SPECIALIZATION ON PHYSICIAN_SPECIALIZATION.id_specialization = PHYSICIAN_HAS_SPECIALIZATION.id_specialization
  WHERE PHYSICIAN_HAS_SPECIALIZATION.id_physician = '';


SELECT PHYSICIAN.id_physician, PHYSICIAN.practice_document
from PHYSICIAN INNER JOIN USER_HEALTH ON
PHYSICIAN.id_user = USER_HEALTH.id_user
WHERE PHYSICIAN.id_user = '';

select * from PHYSICIAN_SPECIALIZATION;

INSERT INTO PHYSICIAN_SPECIALIZATION VALUES (NEWID(), 'Acupuntura', 'Accupunture', 'BRA');
INSERT INTO PHYSICIAN_SPECIALIZATION VALUES (NEWID(), 'Alergia e Imunologia','Allergy' , 'BRA');


INSERT INTO PHYSICIAN_SPECIALIZATION VALUES (NEWID(), 'Africano especializacao', 'specialization', 'FS');
INSERT INTO PHYSICIAN_SPECIALIZATION VALUES (NEWID(), 'Africano especializacao1','specialization' , 'FS');


INSERT INTO PHYSICIAN_SPECIALIZATION VALUES (NEWID(), 'Anestesiologia', 'BRA');
INSERT INTO PHYSICIAN_SPECIALIZATION VALUES (NEWID(), 'Angiologia', 'BRA');
INSERT INTO PHYSICIAN_SPECIALIZATION VALUES (NEWID(), 'Cancerologia', 'BRA');
INSERT INTO PHYSICIAN_SPECIALIZATION VALUES (NEWID(), 'Cardiologia', 'BRA');
INSERT INTO PHYSICIAN_SPECIALIZATION VALUES (NEWID(), 'Cirurgia Cardiovascular', 'BRA');
INSERT INTO PHYSICIAN_SPECIALIZATION VALUES (NEWID(), 'Cirurgia da Mão', 'BRA');
INSERT INTO PHYSICIAN_SPECIALIZATION VALUES (NEWID(), 'Cirurgia de Cabeça e Pescoço', 'BRA');
INSERT INTO PHYSICIAN_SPECIALIZATION VALUES (NEWID(), 'Cirurgia do Aparelho Digestivo', 'BRA');
INSERT INTO PHYSICIAN_SPECIALIZATION VALUES (NEWID(), 'Cirurgia Geral', 'BRA');
INSERT INTO PHYSICIAN_SPECIALIZATION VALUES (NEWID(), 'Cirurgia Pediátrica', 'BRA');
INSERT INTO PHYSICIAN_SPECIALIZATION VALUES (NEWID(), 'Cirurgia Plástica', 'BRA');
INSERT INTO PHYSICIAN_SPECIALIZATION VALUES (NEWID(), 'Cirurgia Torácica', 'BRA');
INSERT INTO PHYSICIAN_SPECIALIZATION VALUES (NEWID(), 'Cirurgia Vascular', 'BRA');
INSERT INTO PHYSICIAN_SPECIALIZATION VALUES (NEWID(), 'Clínica Médica', 'BRA');
INSERT INTO PHYSICIAN_SPECIALIZATION VALUES (NEWID(), 'Coloproctologia', 'BRA');
INSERT INTO PHYSICIAN_SPECIALIZATION VALUES (NEWID(), 'Dermatologia', 'BRA');
INSERT INTO PHYSICIAN_SPECIALIZATION VALUES (NEWID(), 'Endocrinologia e Metabologia', 'BRA');
INSERT INTO PHYSICIAN_SPECIALIZATION VALUES (NEWID(), 'Endoscopia', 'BRA');
INSERT INTO PHYSICIAN_SPECIALIZATION VALUES (NEWID(), 'Gastroenterologia', 'BRA');
INSERT INTO PHYSICIAN_SPECIALIZATION VALUES (NEWID(), 'Genética Médica', 'BRA');
INSERT INTO PHYSICIAN_SPECIALIZATION VALUES (NEWID(), 'Geriatria', 'BRA');
INSERT INTO PHYSICIAN_SPECIALIZATION VALUES (NEWID(), 'Ginecologia e Obstetrícia', 'BRA');
INSERT INTO PHYSICIAN_SPECIALIZATION VALUES (NEWID(), 'Hematologia e Hemoterapia', 'BRA');
INSERT INTO PHYSICIAN_SPECIALIZATION VALUES (NEWID(), 'Homeopatia', 'BRA');
INSERT INTO PHYSICIAN_SPECIALIZATION VALUES (NEWID(), 'Infectologia', 'BRA');
INSERT INTO PHYSICIAN_SPECIALIZATION VALUES (NEWID(), 'Mastologia', 'BRA');
INSERT INTO PHYSICIAN_SPECIALIZATION VALUES (NEWID(), 'Medicina de Família e Comunidade', 'BRA');
INSERT INTO PHYSICIAN_SPECIALIZATION VALUES (NEWID(), 'Medicina do Trabalho', 'BRA');
INSERT INTO PHYSICIAN_SPECIALIZATION VALUES (NEWID(), 'Medicina de Tráfego', 'BRA');
INSERT INTO PHYSICIAN_SPECIALIZATION VALUES (NEWID(), 'Medicina Esportiva', 'BRA');
INSERT INTO PHYSICIAN_SPECIALIZATION VALUES (NEWID(), 'Medicina Física e Reabilitação', 'BRA');
INSERT INTO PHYSICIAN_SPECIALIZATION VALUES (NEWID(), 'Medicina Intensiva', 'BRA');
INSERT INTO PHYSICIAN_SPECIALIZATION VALUES (NEWID(), 'Medicina Legal e Perícia Médica', 'BRA');
INSERT INTO PHYSICIAN_SPECIALIZATION VALUES (NEWID(), 'Medicina Nuclear', 'BRA');
INSERT INTO PHYSICIAN_SPECIALIZATION VALUES (NEWID(), 'Medicina Preventiva e Social', 'BRA');
INSERT INTO PHYSICIAN_SPECIALIZATION VALUES (NEWID(), 'Nefrologia', 'BRA');
INSERT INTO PHYSICIAN_SPECIALIZATION VALUES (NEWID(), 'Neurocirurgia', 'BRA');
INSERT INTO PHYSICIAN_SPECIALIZATION VALUES (NEWID(), 'Neurologia', 'BRA');
INSERT INTO PHYSICIAN_SPECIALIZATION VALUES (NEWID(), 'Nutrologia', 'BRA');
INSERT INTO PHYSICIAN_SPECIALIZATION VALUES (NEWID(), 'Oftalmologia', 'BRA');
INSERT INTO PHYSICIAN_SPECIALIZATION VALUES (NEWID(), 'Ortopedia e Traumatologia', 'BRA');
INSERT INTO PHYSICIAN_SPECIALIZATION VALUES (NEWID(), 'Otorrinolaringologia', 'BRA');
INSERT INTO PHYSICIAN_SPECIALIZATION VALUES (NEWID(), 'Patologia', 'BRA');
INSERT INTO PHYSICIAN_SPECIALIZATION VALUES (NEWID(), 'Patologia Clínica/Medicina Laboratorial', 'BRA');
INSERT INTO PHYSICIAN_SPECIALIZATION VALUES (NEWID(), 'Pediatria', 'BRA');
INSERT INTO PHYSICIAN_SPECIALIZATION VALUES (NEWID(), 'Pneumologia', 'BRA');
INSERT INTO PHYSICIAN_SPECIALIZATION VALUES (NEWID(), 'Psiquiatria', 'BRA');
INSERT INTO PHYSICIAN_SPECIALIZATION VALUES (NEWID(), 'Radiologia e Diagnóstico por Imagem', 'BRA');
INSERT INTO PHYSICIAN_SPECIALIZATION VALUES (NEWID(), 'Radioterapia', 'BRA');
INSERT INTO PHYSICIAN_SPECIALIZATION VALUES (NEWID(), 'Reumatologia', 'BRA');
INSERT INTO PHYSICIAN_SPECIALIZATION VALUES (NEWID(), 'Urologia', 'BRA');





INSERT INTO PHYSICIAN_SPECIALIZATION VALUES(NEWID(), 'Addiction Psychiatrist', 'FS');
INSERT INTO PHYSICIAN_SPECIALIZATION VALUES(NEWID(), 'Addictions', 'FS');
INSERT INTO PHYSICIAN_SPECIALIZATION VALUES(NEWID(), 'ADHD Coaches', 'FS');
INSERT INTO PHYSICIAN_SPECIALIZATION VALUES(NEWID(), 'Adolescent Counsellors', 'FS');
INSERT INTO PHYSICIAN_SPECIALIZATION VALUES(NEWID(), 'Adoption Counsellors', 'FS');
INSERT INTO PHYSICIAN_SPECIALIZATION VALUES(NEWID(), 'Advertisers', 'FS');
INSERT INTO PHYSICIAN_SPECIALIZATION VALUES(NEWID(), 'Aesthetic Gynaecologists', 'FS');
INSERT INTO PHYSICIAN_SPECIALIZATION VALUES(NEWID(), 'Aesthetic Medicine Specialists', 'FS');
INSERT INTO PHYSICIAN_SPECIALIZATION VALUES(NEWID(), 'Age Management Specialists', 'FS');
INSERT INTO PHYSICIAN_SPECIALIZATION VALUES(NEWID(), 'Allergist & Immunologists', 'FS');
INSERT INTO PHYSICIAN_SPECIALIZATION VALUES(NEWID(), 'Anaesthesiologists', 'FS');
INSERT INTO PHYSICIAN_SPECIALIZATION VALUES(NEWID(), 'Anti Aging Specialists', 'FS');
INSERT INTO PHYSICIAN_SPECIALIZATION VALUES(NEWID(), 'Associations', 'FS');
INSERT INTO PHYSICIAN_SPECIALIZATION VALUES(NEWID(), 'Audiologists', 'FS');
INSERT INTO PHYSICIAN_SPECIALIZATION VALUES(NEWID(), 'Ayurveda Physicians', 'FS');
INSERT INTO PHYSICIAN_SPECIALIZATION VALUES(NEWID(), 'Bariatric Medicine Specialists', 'FS');
INSERT INTO PHYSICIAN_SPECIALIZATION VALUES(NEWID(), 'Bariatric/Metabolic Surgeons', 'FS');
INSERT INTO PHYSICIAN_SPECIALIZATION VALUES(NEWID(), 'Biokineticists', 'FS');
INSERT INTO PHYSICIAN_SPECIALIZATION VALUES(NEWID(), 'Cardiac Electrophysiologist', 'FS');
INSERT INTO PHYSICIAN_SPECIALIZATION VALUES(NEWID(), 'Cardiologists', 'FS');
INSERT INTO PHYSICIAN_SPECIALIZATION VALUES(NEWID(), 'Cardiothoracic Surgeons', 'FS');
INSERT INTO PHYSICIAN_SPECIALIZATION VALUES(NEWID(), 'Certified Diabetes Educators', 'FS');
INSERT INTO PHYSICIAN_SPECIALIZATION VALUES(NEWID(), 'Chiropractors', 'FS');
INSERT INTO PHYSICIAN_SPECIALIZATION VALUES(NEWID(), 'Clinical Metal Toxicologists', 'FS');
INSERT INTO PHYSICIAN_SPECIALIZATION VALUES(NEWID(), 'Clinical Nutritionists', 'FS');
INSERT INTO PHYSICIAN_SPECIALIZATION VALUES(NEWID(), 'Clinical Psychologists', 'FS');
INSERT INTO PHYSICIAN_SPECIALIZATION VALUES(NEWID(), 'Clinics', 'FS');
INSERT INTO PHYSICIAN_SPECIALIZATION VALUES(NEWID(), 'Cosmetic and Reconstructive Breast Surgeon', 'FS');
INSERT INTO PHYSICIAN_SPECIALIZATION VALUES(NEWID(), 'Counselling Psychologists', 'FS');
INSERT INTO PHYSICIAN_SPECIALIZATION VALUES(NEWID(), 'Critical Care Medicine Specialists', 'FS');
INSERT INTO PHYSICIAN_SPECIALIZATION VALUES(NEWID(), 'Dental Hygienists', 'FS');
INSERT INTO PHYSICIAN_SPECIALIZATION VALUES(NEWID(), 'Dental Laboratories', 'FS');
INSERT INTO PHYSICIAN_SPECIALIZATION VALUES(NEWID(), 'Dental Therapists', 'FS');
INSERT INTO PHYSICIAN_SPECIALIZATION VALUES(NEWID(), 'Dentists', 'FS');
INSERT INTO PHYSICIAN_SPECIALIZATION VALUES(NEWID(), 'Dermatologists', 'FS');
INSERT INTO PHYSICIAN_SPECIALIZATION VALUES(NEWID(), 'Diabetologist', 'FS');
INSERT INTO PHYSICIAN_SPECIALIZATION VALUES(NEWID(), 'Dieticians', 'FS');
INSERT INTO PHYSICIAN_SPECIALIZATION VALUES(NEWID(), 'DNA Tests', 'FS');
INSERT INTO PHYSICIAN_SPECIALIZATION VALUES(NEWID(), 'Ear, Nose & Throat Surgeon/Otolaryngologists', 'FS');
INSERT INTO PHYSICIAN_SPECIALIZATION VALUES(NEWID(), 'Educational Psychologists', 'FS');
INSERT INTO PHYSICIAN_SPECIALIZATION VALUES(NEWID(), 'Emergency Medicine Specialists', 'FS');
INSERT INTO PHYSICIAN_SPECIALIZATION VALUES(NEWID(), 'Emergency Operations', 'FS');
INSERT INTO PHYSICIAN_SPECIALIZATION VALUES(NEWID(), 'Endocrinologists', 'FS');
INSERT INTO PHYSICIAN_SPECIALIZATION VALUES(NEWID(), 'Endodontists', 'FS');
INSERT INTO PHYSICIAN_SPECIALIZATION VALUES(NEWID(), 'Family Counsellors', 'FS');
INSERT INTO PHYSICIAN_SPECIALIZATION VALUES(NEWID(), 'Family Medicine Specialists', 'FS');
INSERT INTO PHYSICIAN_SPECIALIZATION VALUES(NEWID(), 'Forensic Odontologists', 'FS');
INSERT INTO PHYSICIAN_SPECIALIZATION VALUES(NEWID(), 'Forensic Psychologists', 'FS');
INSERT INTO PHYSICIAN_SPECIALIZATION VALUES(NEWID(), 'Gastroenterologists', 'FS');
INSERT INTO PHYSICIAN_SPECIALIZATION VALUES(NEWID(), 'General Practitioners', 'FS');
INSERT INTO PHYSICIAN_SPECIALIZATION VALUES(NEWID(), 'General Surgeons', 'FS');
INSERT INTO PHYSICIAN_SPECIALIZATION VALUES(NEWID(), 'Genetic Counsellors', 'FS');
INSERT INTO PHYSICIAN_SPECIALIZATION VALUES(NEWID(), 'Geriatric Medicine Specialists', 'FS');
INSERT INTO PHYSICIAN_SPECIALIZATION VALUES(NEWID(), 'Gynaecological Oncologists', 'FS');
INSERT INTO PHYSICIAN_SPECIALIZATION VALUES(NEWID(), 'Gynaecologists', 'FS');
INSERT INTO PHYSICIAN_SPECIALIZATION VALUES(NEWID(), 'Gynaecologists & Obstetricians', 'FS');
INSERT INTO PHYSICIAN_SPECIALIZATION VALUES(NEWID(), 'Haematologists', 'FS');
INSERT INTO PHYSICIAN_SPECIALIZATION VALUES(NEWID(), 'Hand Surgeons', 'FS');
INSERT INTO PHYSICIAN_SPECIALIZATION VALUES(NEWID(), 'Hand Therapists', 'FS');
INSERT INTO PHYSICIAN_SPECIALIZATION VALUES(NEWID(), 'Health Care', 'FS');
INSERT INTO PHYSICIAN_SPECIALIZATION VALUES(NEWID(), 'Health Centre', 'FS');
INSERT INTO PHYSICIAN_SPECIALIZATION VALUES(NEWID(), 'Health and Wellness Practioners', 'FS');
INSERT INTO PHYSICIAN_SPECIALIZATION VALUES(NEWID(), 'Hearing Aid Acousticians', 'FS');
INSERT INTO PHYSICIAN_SPECIALIZATION VALUES(NEWID(), 'Holistic Treatments', 'FS');
INSERT INTO PHYSICIAN_SPECIALIZATION VALUES(NEWID(), 'Home Health Care Specialists', 'FS');
INSERT INTO PHYSICIAN_SPECIALIZATION VALUES(NEWID(), 'Homeopaths', 'FS');
INSERT INTO PHYSICIAN_SPECIALIZATION VALUES(NEWID(), 'Hospitals', 'FS');
INSERT INTO PHYSICIAN_SPECIALIZATION VALUES(NEWID(), 'HPB Hepato-Pancreato-Biliary Surgeons', 'FS');
INSERT INTO PHYSICIAN_SPECIALIZATION VALUES(NEWID(), 'Hypnosis Practitioners', 'FS');
INSERT INTO PHYSICIAN_SPECIALIZATION VALUES(NEWID(), 'Industrial Psychologists', 'FS');
INSERT INTO PHYSICIAN_SPECIALIZATION VALUES(NEWID(), 'Infectious Disease Medicine Specialists', 'FS');
INSERT INTO PHYSICIAN_SPECIALIZATION VALUES(NEWID(), 'Integrated Health Practitioners', 'FS');
INSERT INTO PHYSICIAN_SPECIALIZATION VALUES(NEWID(), 'Integrative Medicine', 'FS');
INSERT INTO PHYSICIAN_SPECIALIZATION VALUES(NEWID(), 'Intensive Care', 'FS');
INSERT INTO PHYSICIAN_SPECIALIZATION VALUES(NEWID(), 'Internal Medicine Specialists', 'FS');
INSERT INTO PHYSICIAN_SPECIALIZATION VALUES(NEWID(), 'Kinesiotherapists', 'FS');
INSERT INTO PHYSICIAN_SPECIALIZATION VALUES(NEWID(), 'Laproscopic Surgeons', 'FS');
INSERT INTO PHYSICIAN_SPECIALIZATION VALUES(NEWID(), 'Maxillofacial & Oral Surgeons', 'FS');
INSERT INTO PHYSICIAN_SPECIALIZATION VALUES(NEWID(), 'Medical Accounts Administrators', 'FS');
INSERT INTO PHYSICIAN_SPECIALIZATION VALUES(NEWID(), 'Medical Consultants', 'FS');
INSERT INTO PHYSICIAN_SPECIALIZATION VALUES(NEWID(), 'Medical Genetics', 'FS');
INSERT INTO PHYSICIAN_SPECIALIZATION VALUES(NEWID(), 'Medical Insurance', 'FS');
INSERT INTO PHYSICIAN_SPECIALIZATION VALUES(NEWID(), 'Medical Oncologists', 'FS');
INSERT INTO PHYSICIAN_SPECIALIZATION VALUES(NEWID(), 'Medical Practice Services', 'FS');
INSERT INTO PHYSICIAN_SPECIALIZATION VALUES(NEWID(), 'Medical Tourism', 'FS');
INSERT INTO PHYSICIAN_SPECIALIZATION VALUES(NEWID(), 'Metabolic Medicine Specialists', 'FS');
INSERT INTO PHYSICIAN_SPECIALIZATION VALUES(NEWID(), 'Midwives', 'FS');
INSERT INTO PHYSICIAN_SPECIALIZATION VALUES(NEWID(), 'Mindfulness Based Interventions and Approaches', 'FS');
INSERT INTO PHYSICIAN_SPECIALIZATION VALUES(NEWID(), 'Naprapath', 'FS');
INSERT INTO PHYSICIAN_SPECIALIZATION VALUES(NEWID(), 'Naturopaths', 'FS');
INSERT INTO PHYSICIAN_SPECIALIZATION VALUES(NEWID(), 'Neurologists', 'FS');
INSERT INTO PHYSICIAN_SPECIALIZATION VALUES(NEWID(), 'Neuromusculoskeletal Medicine', 'FS');
INSERT INTO PHYSICIAN_SPECIALIZATION VALUES(NEWID(), 'Neuropsychologists', 'FS');
INSERT INTO PHYSICIAN_SPECIALIZATION VALUES(NEWID(), 'Neurosurgeons', 'FS');
INSERT INTO PHYSICIAN_SPECIALIZATION VALUES(NEWID(), 'Nuclear Medicine Specialists', 'FS');
INSERT INTO PHYSICIAN_SPECIALIZATION VALUES(NEWID(), 'Nurse Practitioners', 'FS');
INSERT INTO PHYSICIAN_SPECIALIZATION VALUES(NEWID(), 'Occupational Health Specialists', 'FS');
INSERT INTO PHYSICIAN_SPECIALIZATION VALUES(NEWID(), 'Occupational Medicine Specialist', 'FS');
INSERT INTO PHYSICIAN_SPECIALIZATION VALUES(NEWID(), 'Occupational Therapists', 'FS');
INSERT INTO PHYSICIAN_SPECIALIZATION VALUES(NEWID(), 'Oncologists', 'FS');
INSERT INTO PHYSICIAN_SPECIALIZATION VALUES(NEWID(), 'Ophthalmologists', 'FS');
INSERT INTO PHYSICIAN_SPECIALIZATION VALUES(NEWID(), 'Optometrists', 'FS');
INSERT INTO PHYSICIAN_SPECIALIZATION VALUES(NEWID(), 'Orthodontists', 'FS');
INSERT INTO PHYSICIAN_SPECIALIZATION VALUES(NEWID(), 'Orthopaedic Surgeons', 'FS');
INSERT INTO PHYSICIAN_SPECIALIZATION VALUES(NEWID(), 'Orthotics & Prosthetic Specialists', 'FS');
INSERT INTO PHYSICIAN_SPECIALIZATION VALUES(NEWID(), 'Osteopaths', 'FS');
INSERT INTO PHYSICIAN_SPECIALIZATION VALUES(NEWID(), 'Paediatric Allergists', 'FS');
INSERT INTO PHYSICIAN_SPECIALIZATION VALUES(NEWID(), 'Paediatric Dentists', 'FS');
INSERT INTO PHYSICIAN_SPECIALIZATION VALUES(NEWID(), 'Paediatric Cardiologists', 'FS');
INSERT INTO PHYSICIAN_SPECIALIZATION VALUES(NEWID(), 'Paediatric Endocrinologist', 'FS');
INSERT INTO PHYSICIAN_SPECIALIZATION VALUES(NEWID(), 'Paediatric Gastroenterologists', 'FS');
INSERT INTO PHYSICIAN_SPECIALIZATION VALUES(NEWID(), 'Paediatric Neurologists', 'FS');
INSERT INTO PHYSICIAN_SPECIALIZATION VALUES(NEWID(), 'Paediatric Pulmonologist', 'FS');
INSERT INTO PHYSICIAN_SPECIALIZATION VALUES(NEWID(), 'Paediatric Surgeons', 'FS');
INSERT INTO PHYSICIAN_SPECIALIZATION VALUES(NEWID(), 'Paediatricians', 'FS');
INSERT INTO PHYSICIAN_SPECIALIZATION VALUES(NEWID(), 'Pain Medicine Specialists', 'FS');
INSERT INTO PHYSICIAN_SPECIALIZATION VALUES(NEWID(), 'Pathologists', 'FS');
INSERT INTO PHYSICIAN_SPECIALIZATION VALUES(NEWID(), 'Periodontists', 'FS');
INSERT INTO PHYSICIAN_SPECIALIZATION VALUES(NEWID(), 'Personal Injury Practitioners', 'FS');
INSERT INTO PHYSICIAN_SPECIALIZATION VALUES(NEWID(), 'Personal Trainers', 'FS');
INSERT INTO PHYSICIAN_SPECIALIZATION VALUES(NEWID(), 'Pharmacist', 'FS');
INSERT INTO PHYSICIAN_SPECIALIZATION VALUES(NEWID(), 'Physical Rehabilitation', 'FS');
INSERT INTO PHYSICIAN_SPECIALIZATION VALUES(NEWID(), 'Physicians', 'FS');
INSERT INTO PHYSICIAN_SPECIALIZATION VALUES(NEWID(), 'Physiotherapists', 'FS');
INSERT INTO PHYSICIAN_SPECIALIZATION VALUES(NEWID(), 'Pilates', 'FS');
INSERT INTO PHYSICIAN_SPECIALIZATION VALUES(NEWID(), 'Plastic & Reconstructive Surgeons', 'FS');
INSERT INTO PHYSICIAN_SPECIALIZATION VALUES(NEWID(), 'Podiatrists', 'FS');
INSERT INTO PHYSICIAN_SPECIALIZATION VALUES(NEWID(), 'Preventive Medicine Specialists', 'FS');
INSERT INTO PHYSICIAN_SPECIALIZATION VALUES(NEWID(), 'Prosthodontists', 'FS');
INSERT INTO PHYSICIAN_SPECIALIZATION VALUES(NEWID(), 'Psychiatrists', 'FS');
INSERT INTO PHYSICIAN_SPECIALIZATION VALUES(NEWID(), 'Psychometrists', 'FS');
INSERT INTO PHYSICIAN_SPECIALIZATION VALUES(NEWID(), 'Psychotherapists', 'FS');
INSERT INTO PHYSICIAN_SPECIALIZATION VALUES(NEWID(), 'Pulmonologists', 'FS');
INSERT INTO PHYSICIAN_SPECIALIZATION VALUES(NEWID(), 'Radiation Oncologists', 'FS');
INSERT INTO PHYSICIAN_SPECIALIZATION VALUES(NEWID(), 'Radiologists', 'FS');
INSERT INTO PHYSICIAN_SPECIALIZATION VALUES(NEWID(), 'Registered Counsellors', 'FS');
INSERT INTO PHYSICIAN_SPECIALIZATION VALUES(NEWID(), 'Registered Radiographers', 'FS');
INSERT INTO PHYSICIAN_SPECIALIZATION VALUES(NEWID(), 'Registered Rehabilitation Centre', 'FS');
INSERT INTO PHYSICIAN_SPECIALIZATION VALUES(NEWID(), 'Reproductive Medicine Specialists', 'FS');
INSERT INTO PHYSICIAN_SPECIALIZATION VALUES(NEWID(), 'Rheumatologists', 'FS');
INSERT INTO PHYSICIAN_SPECIALIZATION VALUES(NEWID(), 'Rhinoplasty Surgeons', 'FS');
INSERT INTO PHYSICIAN_SPECIALIZATION VALUES(NEWID(), 'Robotic Surgeons', 'FS');
INSERT INTO PHYSICIAN_SPECIALIZATION VALUES(NEWID(), 'Sexologists', 'FS');
INSERT INTO PHYSICIAN_SPECIALIZATION VALUES(NEWID(), 'Sexual Medicine', 'FS');
INSERT INTO PHYSICIAN_SPECIALIZATION VALUES(NEWID(), 'Sleep Disorder Specialists', 'FS');
INSERT INTO PHYSICIAN_SPECIALIZATION VALUES(NEWID(), 'Social Responsibility', 'FS');
INSERT INTO PHYSICIAN_SPECIALIZATION VALUES(NEWID(), 'Social Workers', 'FS');
INSERT INTO PHYSICIAN_SPECIALIZATION VALUES(NEWID(), 'Specialist Surgeons', 'FS');
INSERT INTO PHYSICIAN_SPECIALIZATION VALUES(NEWID(), 'Speech Therapists', 'FS');
INSERT INTO PHYSICIAN_SPECIALIZATION VALUES(NEWID(), 'Sports Medicine Specialists', 'FS');
INSERT INTO PHYSICIAN_SPECIALIZATION VALUES(NEWID(), 'Therapists', 'FS');
INSERT INTO PHYSICIAN_SPECIALIZATION VALUES(NEWID(), 'Trauma Counsellors', 'FS');
INSERT INTO PHYSICIAN_SPECIALIZATION VALUES(NEWID(), 'Urologists', 'FS');
INSERT INTO PHYSICIAN_SPECIALIZATION VALUES(NEWID(), 'Vascular Surgeons', 'FS');
INSERT INTO PHYSICIAN_SPECIALIZATION VALUES(NEWID(), 'Womens Health Specialists', 'FS');



INSERT INTO NURSE_SPECIALIZATION VALUES (NEWID(), 'Aeroespacial',  'Aerospace', 'BRA');
INSERT INTO NURSE_SPECIALIZATION VALUES (NEWID(), 'Assistência ao Adolescente', 'Adolecent', 'BRA');

INSERT INTO NURSE_SPECIALIZATION VALUES (NEWID(), 'Atendimento Pré-Hospitalar','pre hospital', 'FS');
INSERT INTO NURSE_SPECIALIZATION VALUES (NEWID(), 'Banco de Leite Humano', 'human milk bank', 'FS');


INSERT INTO NURSE_SPECIALIZATION VALUES (NEWID(), 'Cardiovascular', 'BRA');
INSERT INTO NURSE_SPECIALIZATION VALUES (NEWID(), 'Central de Material e Esterilização', 'BRA');
INSERT INTO NURSE_SPECIALIZATION VALUES (NEWID(), 'Centro Cirúrgico', 'BRA');
INSERT INTO NURSE_SPECIALIZATION VALUES (NEWID(), 'Clínica Cirúrgica', 'BRA');
INSERT INTO NURSE_SPECIALIZATION VALUES (NEWID(), 'Clínica Médica', 'BRA');
INSERT INTO NURSE_SPECIALIZATION VALUES (NEWID(), 'Dermatologia', 'BRA');
INSERT INTO NURSE_SPECIALIZATION VALUES (NEWID(), 'Diagnóstico por Imagem', 'BRA');
INSERT INTO NURSE_SPECIALIZATION VALUES (NEWID(), 'Doenças Infecciosas', 'BRA');
INSERT INTO NURSE_SPECIALIZATION VALUES (NEWID(), 'Educação em Enfermagem', 'BRA');
INSERT INTO NURSE_SPECIALIZATION VALUES (NEWID(), 'Emergência', 'BRA');
INSERT INTO NURSE_SPECIALIZATION VALUES (NEWID(), 'Endocrinologia', 'BRA');
INSERT INTO NURSE_SPECIALIZATION VALUES (NEWID(), 'Endoscopia', 'BRA');
INSERT INTO NURSE_SPECIALIZATION VALUES (NEWID(), 'Estomaterapia', 'BRA');
INSERT INTO NURSE_SPECIALIZATION VALUES (NEWID(), 'Ética e Bioética', 'BRA');
INSERT INTO NURSE_SPECIALIZATION VALUES (NEWID(), 'Gerenciamento de Serviços de Saúde', 'BRA');
INSERT INTO NURSE_SPECIALIZATION VALUES (NEWID(), 'Gerontologia e Geriatria', 'BRA');
INSERT INTO NURSE_SPECIALIZATION VALUES (NEWID(), 'Ginecologia', 'BRA');
INSERT INTO NURSE_SPECIALIZATION VALUES (NEWID(), 'Hemo dinâmica', 'BRA');
INSERT INTO NURSE_SPECIALIZATION VALUES (NEWID(), 'Homecare', 'BRA');
INSERT INTO NURSE_SPECIALIZATION VALUES (NEWID(), 'Infecção Hospitalar', 'BRA');
INSERT INTO NURSE_SPECIALIZATION VALUES (NEWID(), 'Informática', 'BRA');
INSERT INTO NURSE_SPECIALIZATION VALUES (NEWID(), 'Nefrologia', 'BRA');
INSERT INTO NURSE_SPECIALIZATION VALUES (NEWID(), 'Neonatologia', 'BRA');
INSERT INTO NURSE_SPECIALIZATION VALUES (NEWID(), 'Nutrição Parenteral', 'BRA');
INSERT INTO NURSE_SPECIALIZATION VALUES (NEWID(), 'Obstetrícia', 'BRA');
INSERT INTO NURSE_SPECIALIZATION VALUES (NEWID(), 'Oftalmologia', 'BRA');
INSERT INTO NURSE_SPECIALIZATION VALUES (NEWID(), 'Oncologia', 'BRA');
INSERT INTO NURSE_SPECIALIZATION VALUES (NEWID(), 'Otorrinolaringologia', 'BRA');
INSERT INTO NURSE_SPECIALIZATION VALUES (NEWID(), 'Pediatria', 'BRA');
INSERT INTO NURSE_SPECIALIZATION VALUES (NEWID(), 'Perícia e Auditoria', 'BRA');
INSERT INTO NURSE_SPECIALIZATION VALUES (NEWID(), 'Psiquiatria e Saúde Mental', 'BRA');
INSERT INTO NURSE_SPECIALIZATION VALUES (NEWID(), 'Saúde Coletiva', 'BRA');
INSERT INTO NURSE_SPECIALIZATION VALUES (NEWID(), 'Saúde da Família', 'BRA');
INSERT INTO NURSE_SPECIALIZATION VALUES (NEWID(), 'Sexologia Humana', 'BRA');
INSERT INTO NURSE_SPECIALIZATION VALUES (NEWID(), 'Trabalho', 'BRA');
INSERT INTO NURSE_SPECIALIZATION VALUES (NEWID(), 'Traumato-Ortopedia', 'BRA');
INSERT INTO NURSE_SPECIALIZATION VALUES (NEWID(), 'Terapia Intensiva', 'BRA');
INSERT INTO NURSE_SPECIALIZATION VALUES (NEWID(), 'Terapias Naturais/Tradicionais e Complementares/Não Convencionais', 'BRA');





INSERT INTO NURSE_SPECIALIZATION VALUES (NEWID(), 'Primary health care', 'FS');
INSERT INTO NURSE_SPECIALIZATION VALUES (NEWID(), 'Management', 'FS');
INSERT INTO NURSE_SPECIALIZATION VALUES (NEWID(), 'Occupational', 'FS');
INSERT INTO NURSE_SPECIALIZATION VALUES (NEWID(), 'Health Orthopaedic', 'FS');
INSERT INTO NURSE_SPECIALIZATION VALUES (NEWID(), 'ICU', 'FS');
INSERT INTO NURSE_SPECIALIZATION VALUES (NEWID(), 'Trauma Paeds', 'FS');
INSERT INTO NURSE_SPECIALIZATION VALUES (NEWID(), 'Advanced Midwifery', 'FS');
INSERT INTO NURSE_SPECIALIZATION VALUES (NEWID(), 'Opthalmology', 'FS');
INSERT INTO NURSE_SPECIALIZATION VALUES (NEWID(), 'Theatre tech', 'FS');
INSERT INTO NURSE_SPECIALIZATION VALUES (NEWID(), 'Intensive care', 'FS');
INSERT INTO NURSE_SPECIALIZATION VALUES (NEWID(), 'Pediatrics', 'FS');
INSERT INTO NURSE_SPECIALIZATION VALUES (NEWID(), 'Orthopedics', 'FS');

insert into diagnosis (id_diagnosis,anotation, id_patient, id_physician, id_health_institution) values(NEWID(),'teste', '400973e0-a178-4fcb-ba26-48839018d601', '0aea4791-d5f5-4061-bca7-8f42a329a287',
'138a2cc4-0b02-4a14-89b2-a318bbf7e34a');


SELECT * FROM DIAGNOSIS;

SELECT D.id_diagnosis, D.date_diagnosis, D.anotation, D.id_patient, D.id_physician, D.id_health_institution,
H.name, P.practice_document, U.name as pname
FROM DIAGNOSIS AS D
INNER JOIN HEALTH_INSTITUTION AS H ON
D.id_health_institution = H.id_health_institution
INNER JOIN PHYSICIAN AS P ON 
P.id_physician = D.id_physician
INNER JOIN (select  name, id_physician from PHYSICIAN INNER JOIN USER_HEALTH
ON USER_HEALTH.id_user = PHYSICIAN.id_user) AS U ON
P.id_physician = U.id_physician
WHERE D.id_patient = '400973e0-a178-4fcb-ba26-48839018d601'
AND P.id_physician = '0aea4791-d5f5-4061-bca7-8f42a329a287';

SELECT E.id_exam, E.date_exam, E.anotation, E.id_patient, E.id_physician, E.id_health_institution, 
				H.name, H.photo as hphoto, H.latitute, H.longitute, P.practice_document, U.name as pname, U.country as pcountry, U.photo as pphoto  FROM EXAM AS E 
				INNER JOIN HEALTH_INSTITUTION AS H ON  E.id_health_institution = H.id_health_institution 
				INNER JOIN PHYSICIAN AS P ON  P.id_physician = E.id_physician 
				INNER JOIN (select  name, id_physician, country, photo from PHYSICIAN INNER JOIN USER_HEALTH 
				ON USER_HEALTH.id_user = PHYSICIAN.id_user) AS U ON P.id_physician = U.id_physician 
				
				INNER JOIN (SELECT COUNT(*) FROM EXAM_ATTACHMENT INNER JOIN EXAM ON EXAM.id_exam = EXAM_ATTACHMENT.id_exam)
				AS EA
				WHERE E.id_patient = 'F8313B58-F807-4098-A74B-64BF456FA838' ORDER BY date_exam DESC;

select * from PATIENT_HAS_TAG;