drop table medicine;
CREATE TABLE MEDICINE(
	id_medicine CHAR(36) PRIMARY KEY,
	name VARCHAR(100) NOT NULL,
	language VARCHAR(03) NOT NULL,
	country VARCHAR(03) NOT NULL,
	status CHAR(01) NOT NULL --0  - DISABLE 1 - ENABLE
);


INSERT INTO MEDICINE VALUES(NEWID(), 'Abacavir', 'en','FS', '1');
INSERT INTO MEDICINE VALUES(NEWID(), 'ACE-Inhibitor','en', 'FS', '1');
INSERT INTO MEDICINE VALUES(NEWID(), 'Acetazolamide', 'en','FS', '1');
INSERT INTO MEDICINE VALUES(NEWID(), 'Acetic Acid', 'en','FS', '1');
INSERT INTO MEDICINE VALUES(NEWID(), 'Aciclovir', 'en','FS', '1');
INSERT INTO MEDICINE VALUES(NEWID(), 'Activated charcoal','en', 'FS', '1');
INSERT INTO MEDICINE VALUES(NEWID(), 'Albendazole', 'en','FS', '1');
INSERT INTO MEDICINE VALUES(NEWID(), 'Allopurinol', 'en','FS', '1');
INSERT INTO MEDICINE VALUES(NEWID(), 'Aminoglycosides','en', 'FS', '1');
INSERT INTO MEDICINE VALUES(NEWID(), 'Amitriptyline', 'en','FS', '1');
INSERT INTO MEDICINE VALUES(NEWID(), 'Amlodipine', 'en','FS', '1');
INSERT INTO MEDICINE VALUES(NEWID(), 'Amoxicillin','en', 'FS', '1');
INSERT INTO MEDICINE VALUES(NEWID(), 'Amoxicillin/Clavulanic Acid', 'en','FS', '1');
INSERT INTO MEDICINE VALUES(NEWID(), 'Ampicillin', 'en','FS', '1');
INSERT INTO MEDICINE VALUES(NEWID(), 'Anticholinergic', 'en','FS', '1');
INSERT INTO MEDICINE VALUES(NEWID(), 'Anticholinergic','en', 'FS', '1');
INSERT INTO MEDICINE VALUES(NEWID(), 'Anticholinergic', 'en','FS', '1');
INSERT INTO MEDICINE VALUES(NEWID(), 'Anti-D immunoglobulin', 'en','FS', '1');
INSERT INTO MEDICINE VALUES(NEWID(), 'Aqueous Cream', 'en','FS', '1');
INSERT INTO MEDICINE VALUES(NEWID(), 'ARB', 'en','FS', '1');
INSERT INTO MEDICINE VALUES(NEWID(), 'Artemether/lumefantrine', 'en','FS', '1');
INSERT INTO MEDICINE VALUES(NEWID(), 'Artesunate', 'en','FS', '1');
INSERT INTO MEDICINE VALUES(NEWID(), 'Aspirin', 'en','FS', '1');
INSERT INTO MEDICINE VALUES(NEWID(), 'Atazanavir/ritonavir','en', 'FS', '1');
INSERT INTO MEDICINE VALUES(NEWID(), 'Atenolol', 'en','FS', '1');
INSERT INTO MEDICINE VALUES(NEWID(), 'Atropine', 'en','FS', '1');
INSERT INTO MEDICINE VALUES(NEWID(), 'Atropine, opthalmic', 'en', 'FS', '1');
INSERT INTO MEDICINE VALUES(NEWID(), 'Azithromycin', 'en','FS', '1');
INSERT INTO MEDICINE VALUES(NEWID(), 'ß-blocker', 'en','FS', '1');
INSERT INTO MEDICINE VALUES(NEWID(), 'BCG vaccine', 'en','FS', '1');
INSERT INTO MEDICINE VALUES(NEWID(), 'Beclomethasone','en', 'FS', '1');
INSERT INTO MEDICINE VALUES(NEWID(), 'Benyl Benzoate', 'en','FS', '1');
INSERT INTO MEDICINE VALUES(NEWID(), 'Benzathine benzylpenicillin', 'en','FS', '1');
INSERT INTO MEDICINE VALUES(NEWID(), 'Benzodiazepines, oral', 'en','FS', '1');
INSERT INTO MEDICINE VALUES(NEWID(), 'Benzodiazepines, parenteral', 'en','FS', '1');
INSERT INTO MEDICINE VALUES(NEWID(), 'Benzoyl peroxide', 'en','FS', '1');
INSERT INTO MEDICINE VALUES(NEWID(), 'Benzyl benzoate', 'en','FS', '1');
INSERT INTO MEDICINE VALUES(NEWID(), 'Beta2 agonists, inhaler', 'en','FS', '1');
INSERT INTO MEDICINE VALUES(NEWID(), 'Betamethasone','en', 'FS', '1');
INSERT INTO MEDICINE VALUES(NEWID(), 'Betamethasone, topical', 'en','FS', '1');
INSERT INTO MEDICINE VALUES(NEWID(), 'Biperiden', 'en','FS', '1');
INSERT INTO MEDICINE VALUES(NEWID(), 'BIPP stripping', 'en','FS', '1');
INSERT INTO MEDICINE VALUES(NEWID(), 'Bismuth subgallate compound, ointment', 'en','FS', '1');
INSERT INTO MEDICINE VALUES(NEWID(), 'Bismuth subgallate compound, suppositries', 'en','FS', '1');
INSERT INTO MEDICINE VALUES(NEWID(), 'Blood glucose monitoring', 'en','FS', '1');
INSERT INTO MEDICINE VALUES(NEWID(), 'Budesonide, nasal spray', 'en','FS', '1');
INSERT INTO MEDICINE VALUES(NEWID(), 'Calamine lotion', 'en','FS', '1');
INSERT INTO MEDICINE VALUES(NEWID(), 'Calcium', 'en','FS', '1');
INSERT INTO MEDICINE VALUES(NEWID(), 'Calcium Carbonate', 'en','FS', '1');
INSERT INTO MEDICINE VALUES(NEWID(), 'Capreomycin', 'en','FS', '1');
INSERT INTO MEDICINE VALUES(NEWID(), 'Carbamazepine', 'en','FS', '1');
INSERT INTO MEDICINE VALUES(NEWID(), 'Carvedilol', 'en','FS', '1');
INSERT INTO MEDICINE VALUES(NEWID(), 'Ceftriaxone', 'en','FS', '1');
INSERT INTO MEDICINE VALUES(NEWID(), 'Cephalexin', 'en','FS', '1');
INSERT INTO MEDICINE VALUES(NEWID(), 'Cetirizine', 'en','FS', '1');
INSERT INTO MEDICINE VALUES(NEWID(), 'Chloramphenicol, opthalmic','en', 'FS', '1');
INSERT INTO MEDICINE VALUES(NEWID(), 'Chlorhexidine 0.05% aqueous solution', 'en','FS', '1');
INSERT INTO MEDICINE VALUES(NEWID(), 'Chlorhexidine 0.05% solution','en', 'FS', '1');
INSERT INTO MEDICINE VALUES(NEWID(), 'Chlorhexidine 0.2% mouthwash','en', 'FS', '1');
INSERT INTO MEDICINE VALUES(NEWID(), 'Chlorhexidine 0.5% in 70% alcohol', 'en','FS', '1');
INSERT INTO MEDICINE VALUES(NEWID(), 'Chlorphenamine', 'en','FS', '1');
INSERT INTO MEDICINE VALUES(NEWID(), 'Chlorpromazine', 'en','FS', '1');
INSERT INTO MEDICINE VALUES(NEWID(), 'Ciprofloxacin','en', 'FS', '1');
INSERT INTO MEDICINE VALUES(NEWID(), 'Citalopram', 'en','FS', '1');
INSERT INTO MEDICINE VALUES(NEWID(), 'Clotrimazole, topical', 'en','FS', '1');
INSERT INTO MEDICINE VALUES(NEWID(), 'Clotrimazole, vaginal cream', 'en','FS', '1');
INSERT INTO MEDICINE VALUES(NEWID(), 'Clotrimazole, vaginal pessary', 'en','FS', '1');
INSERT INTO MEDICINE VALUES(NEWID(), 'Coal tar (LPC), topical','en', 'FS', '1');
INSERT INTO MEDICINE VALUES(NEWID(), 'Combined oral contraceptive (Estrogen/progestin)','en', 'FS', '1');
INSERT INTO MEDICINE VALUES(NEWID(), 'Conjugated equine estrogens', 'en','FS', '1');
INSERT INTO MEDICINE VALUES(NEWID(), 'Corticosteroid, nasal', 'en','FS', '1');
INSERT INTO MEDICINE VALUES(NEWID(), 'Cotrimoxazole', 'en','FS', '1');
INSERT INTO MEDICINE VALUES(NEWID(), 'Cough Syrup', 'en','FS', '1');
INSERT INTO MEDICINE VALUES(NEWID(), 'Cyproterone acetate','en', 'FS', '1');
INSERT INTO MEDICINE VALUES(NEWID(), 'Dextrose 5%','en', 'FS', '1');
INSERT INTO MEDICINE VALUES(NEWID(), 'Dextrose (glucose) 10%','en', 'FS', '1');
INSERT INTO MEDICINE VALUES(NEWID(), 'Dextrose 50%','en', 'FS', '1');
INSERT INTO MEDICINE VALUES(NEWID(), 'Diazepam, oral','en', 'FS', '1');
INSERT INTO MEDICINE VALUES(NEWID(), 'Diazepam, parenteral','en', 'FS', '1');
INSERT INTO MEDICINE VALUES(NEWID(), 'Diazepam, rectal','en', 'FS', '1');
INSERT INTO MEDICINE VALUES(NEWID(), 'Didanosine','en', 'FS', '1');
INSERT INTO MEDICINE VALUES(NEWID(), 'Digoxin','en', 'FS', '1');
INSERT INTO MEDICINE VALUES(NEWID(), 'Doxycycline','en', 'FS', '1');
INSERT INTO MEDICINE VALUES(NEWID(), 'Efavirenz','en', 'FS', '1');
INSERT INTO MEDICINE VALUES(NEWID(), 'Emollient', 'en','FS', '1');
INSERT INTO MEDICINE VALUES(NEWID(), 'Emtricitabine', 'en','FS', '1');
INSERT INTO MEDICINE VALUES(NEWID(), 'Emulsifying ointment','en', 'FS', '1');
INSERT INTO MEDICINE VALUES(NEWID(), 'Enalapril', 'en','FS', '1');
INSERT INTO MEDICINE VALUES(NEWID(), 'Epinephrine (adrenaline)', 'en','FS', '1');
INSERT INTO MEDICINE VALUES(NEWID(), 'Epinephrine (adrenaline), inhalation', 'en','FS', '1');
INSERT INTO MEDICINE VALUES(NEWID(), 'Ergometrine', 'en','FS', '1');
INSERT INTO MEDICINE VALUES(NEWID(), 'Erythromycin', 'en','FS', '1');
INSERT INTO MEDICINE VALUES(NEWID(), 'Estradiol valerate', 'en','FS', '1');
INSERT INTO MEDICINE VALUES(NEWID(), 'Ethambutol', 'en','FS', '1');
INSERT INTO MEDICINE VALUES(NEWID(), 'Ethinyloestradiol/levonorgestrel', 'en','FS', '1');
INSERT INTO MEDICINE VALUES(NEWID(), 'Ethinyloestradiol/levonorgestrel 30mcg/150 mcg', 'en','FS', '1');
INSERT INTO MEDICINE VALUES(NEWID(), 'Ethionamide', 'en','FS', '1');
INSERT INTO MEDICINE VALUES(NEWID(), 'Etonogestrel', 'en','FS', '1');
INSERT INTO MEDICINE VALUES(NEWID(), 'Ferrous fumarate', 'en','FS', '1');
INSERT INTO MEDICINE VALUES(NEWID(), 'Ferrous gluconate','en', 'FS', '1');
INSERT INTO MEDICINE VALUES(NEWID(), 'Ferrous lactate', 'en','FS', '1');
INSERT INTO MEDICINE VALUES(NEWID(), 'Ferrous sulphate', 'en','FS', '1');
INSERT INTO MEDICINE VALUES(NEWID(), 'Flucloxacillin', 'en','FS', '1');
INSERT INTO MEDICINE VALUES(NEWID(), 'Fluconazole', 'en','FS', '1');
INSERT INTO MEDICINE VALUES(NEWID(), 'Fluoxetine', 'en','FS', '1');
INSERT INTO MEDICINE VALUES(NEWID(), 'Flupenthixol decanoate', 'en','FS', '1');
INSERT INTO MEDICINE VALUES(NEWID(), 'Fluphenazine decanoate', 'en','FS', '1');
INSERT INTO MEDICINE VALUES(NEWID(), 'Fluoroquinolones', 'en','FS', '1');
INSERT INTO MEDICINE VALUES(NEWID(), 'Folic Acid', 'en','FS', '1');
INSERT INTO MEDICINE VALUES(NEWID(), 'Furosemide, oral', 'en','FS', '1');
INSERT INTO MEDICINE VALUES(NEWID(), 'Furosemide, parenteral','en', 'FS', '1');
INSERT INTO MEDICINE VALUES(NEWID(), 'Gentamicin', 'en','FS', '1');
INSERT INTO MEDICINE VALUES(NEWID(), 'Glibenclamide','en', 'FS', '1');
INSERT INTO MEDICINE VALUES(NEWID(), 'Glimepiride','en', 'FS', '1');
INSERT INTO MEDICINE VALUES(NEWID(), 'Haemophilus Influenza type B vaccine','en', 'FS', '1');
INSERT INTO MEDICINE VALUES(NEWID(), 'Haloperidol, oral','en', 'FS', '1');
INSERT INTO MEDICINE VALUES(NEWID(), 'Haloperidol, parenteral','en', 'FS', '1');
INSERT INTO MEDICINE VALUES(NEWID(), 'Hepatitis B vaccine','en', 'FS', '1');
INSERT INTO MEDICINE VALUES(NEWID(), 'Hexavalent - diptheria, tetanus, acellular Pertussis, inactivated polio, hepatitis B, Haemophilus influenza type b vaccine','en', 'FS', '1');
INSERT INTO MEDICINE VALUES(NEWID(), 'HMGCoA reductase inhibitor', 'en', 'FS', '1');
INSERT INTO MEDICINE VALUES(NEWID(), 'Human papillomavirus vaccine','en', 'FS', '1');
INSERT INTO MEDICINE VALUES(NEWID(), 'Hydrochlorothiazide', 'en','FS', '1');
INSERT INTO MEDICINE VALUES(NEWID(), 'Hydrocortisone, parenteral','en', 'FS', '1');
INSERT INTO MEDICINE VALUES(NEWID(), 'Hydrocortisone, topical', 'en','FS', '1');
INSERT INTO MEDICINE VALUES(NEWID(), 'Hyoscine butylbromide','en', 'FS', '1');
INSERT INTO MEDICINE VALUES(NEWID(), 'Ibuprofen', 'en','FS', '1');
INSERT INTO MEDICINE VALUES(NEWID(), 'Imidazole, topical', 'en','FS', '1');
INSERT INTO MEDICINE VALUES(NEWID(), 'Influenza vaccine', 'en','FS', '1');
INSERT INTO MEDICINE VALUES(NEWID(), 'Inhaled corticosteroids, inhaler','en', 'FS', '1');
INSERT INTO MEDICINE VALUES(NEWID(), 'Inhaled long-acting beta agonist/corticosteroid,inhaler','en', 'FS', '1');
INSERT INTO MEDICINE VALUES(NEWID(), 'Insulin','en', 'FS', '1');
INSERT INTO MEDICINE VALUES(NEWID(), 'Insulin, biphasic','en', 'FS', '1');
INSERT INTO MEDICINE VALUES(NEWID(), 'Insulin, cartridges', 'en','FS', '1');
INSERT INTO MEDICINE VALUES(NEWID(), 'Insulin, intermediate acting', 'en','FS', '1'); 
INSERT INTO MEDICINE VALUES(NEWID(), 'Insulin, intermediate-long acting','en', 'FS', '1');
INSERT INTO MEDICINE VALUES(NEWID(), 'Insulin, prefills','en', 'FS', '1');
INSERT INTO MEDICINE VALUES(NEWID(), 'Insulin, short acting','en', 'FS', '1');
INSERT INTO MEDICINE VALUES(NEWID(), 'Ipratropium Bromide, inhaler','en', 'FS', '1');
INSERT INTO MEDICINE VALUES(NEWID(), 'Ipratropium Bromide, solution', 'en','FS', '1');
INSERT INTO MEDICINE VALUES(NEWID(), 'Iron','en', 'FS', '1');
INSERT INTO MEDICINE VALUES(NEWID(), 'Isoniazid','en', 'FS', '1');
INSERT INTO MEDICINE VALUES(NEWID(), 'Isosorbide dinitrate, sublingual','en', 'FS', '1');
INSERT INTO MEDICINE VALUES(NEWID(), 'Isosorbide mononitrate', 'en','FS', '1');
INSERT INTO MEDICINE VALUES(NEWID(), 'IUD (copper)', 'en','FS', '1');
INSERT INTO MEDICINE VALUES(NEWID(), 'Kanamycin', 'en','FS', '1');
INSERT INTO MEDICINE VALUES(NEWID(), 'Lactulose','en', 'FS', '1');
INSERT INTO MEDICINE VALUES(NEWID(), 'Lamivudine', 'en','FS', '1');
INSERT INTO MEDICINE VALUES(NEWID(), 'Lamotrigine', 'en','FS', '1');
INSERT INTO MEDICINE VALUES(NEWID(), 'Lansoprazole', 'en','FS', '1');
INSERT INTO MEDICINE VALUES(NEWID(), 'Levonorgestrel, oral', 'en','FS', '1');
INSERT INTO MEDICINE VALUES(NEWID(), 'Levonorgestrel, subdermal','en', 'FS', '1');
INSERT INTO MEDICINE VALUES(NEWID(), 'Levothyroxine', 'en','FS', '1');
INSERT INTO MEDICINE VALUES(NEWID(), 'Lidocaine 1%, parenteral', 'en','FS', '1');
INSERT INTO MEDICINE VALUES(NEWID(), 'Lidocaine 2%, parenteral', 'en','FS', '1');
INSERT INTO MEDICINE VALUES(NEWID(), 'Lidocaine 2%, topical', 'en','FS', '1');
INSERT INTO MEDICINE VALUES(NEWID(), 'Lidocaine with epinephrine (adrenaline),parenteral','en', 'FS', '1');
INSERT INTO MEDICINE VALUES(NEWID(), 'Lidocaine, parenteral', 'en','FS', '1');
INSERT INTO MEDICINE VALUES(NEWID(), 'Long acting calcium channel blocker', 'en','FS', '1');
INSERT INTO MEDICINE VALUES(NEWID(), 'Loop diuretic','en', 'FS', '1');
INSERT INTO MEDICINE VALUES(NEWID(), 'Loperamide', 'en','FS', '1');
INSERT INTO MEDICINE VALUES(NEWID(), 'Lopinavir/ritonavir', 'en','FS', '1');
INSERT INTO MEDICINE VALUES(NEWID(), 'Macrolide','en', 'FS', '1');
INSERT INTO MEDICINE VALUES(NEWID(), 'Magnesium sulphate, parenteral', 'en','FS', '1');
INSERT INTO MEDICINE VALUES(NEWID(), 'Measles vaccine', 'en','FS', '1');
INSERT INTO MEDICINE VALUES(NEWID(), 'Mebendazole', 'en','FS', '1');
INSERT INTO MEDICINE VALUES(NEWID(), 'Medroxyprogesterone acetate, oral','en', 'FS', '1');
INSERT INTO MEDICINE VALUES(NEWID(), 'Medroxyprogesterone acetate, parenteral','en', 'FS', '1');
INSERT INTO MEDICINE VALUES(NEWID(), 'Metformin', 'en','FS', '1');
INSERT INTO MEDICINE VALUES(NEWID(), 'Methyl salicylate ointment', 'en','FS', '1');
INSERT INTO MEDICINE VALUES(NEWID(), 'Methyldopa', 'en','FS', '1');
INSERT INTO MEDICINE VALUES(NEWID(), 'Metoclopramide, oral', 'en','FS', '1');
INSERT INTO MEDICINE VALUES(NEWID(), 'Metoclopramide, parenteral', 'en','FS', '1');
INSERT INTO MEDICINE VALUES(NEWID(), 'Metronidazole', 'en','FS', '1');
INSERT INTO MEDICINE VALUES(NEWID(), 'Midazolam, buccal', 'en','FS', '1');
INSERT INTO MEDICINE VALUES(NEWID(), 'Midazolam, parenteral', 'en','FS', '1');
INSERT INTO MEDICINE VALUES(NEWID(), 'Misoprostol', 'en','FS', '1');
INSERT INTO MEDICINE VALUES(NEWID(), 'Monophasic: combined estrogen/progestin pills', 'en','FS', '1');
INSERT INTO MEDICINE VALUES(NEWID(), 'Monophasic: progestin only pills', 'en','FS', '1');
INSERT INTO MEDICINE VALUES(NEWID(), 'Morphine, long-acting, oral', 'en','FS', '1');
INSERT INTO MEDICINE VALUES(NEWID(), 'Morphine, oral', 'en','FS', '1');
INSERT INTO MEDICINE VALUES(NEWID(), 'Morphine, parenteral', 'en','FS', '1');
INSERT INTO MEDICINE VALUES(NEWID(), 'Moxifloxacin', 'en','FS', '1');
INSERT INTO MEDICINE VALUES(NEWID(), 'Multivitamin', 'en','FS', '1');
INSERT INTO MEDICINE VALUES(NEWID(), 'N-acetylcysteine', 'en','FS', '1');
INSERT INTO MEDICINE VALUES(NEWID(), 'Naloxone', 'en','FS', '1');
INSERT INTO MEDICINE VALUES(NEWID(), 'Nevirapine', 'en','FS', '1');
INSERT INTO MEDICINE VALUES(NEWID(), 'Nicotinamide', 'en','FS', '1');
INSERT INTO MEDICINE VALUES(NEWID(), 'Nifedipine', 'en','FS', '1');
INSERT INTO MEDICINE VALUES(NEWID(), 'Nitrates, short acting', 'en','FS', '1');
INSERT INTO MEDICINE VALUES(NEWID(), 'Nitrous oxide/oxygen', 'en','FS', '1');
INSERT INTO MEDICINE VALUES(NEWID(), 'Non-nucleoside reverse transcriptase inhibitor', 'en','FS', '1');
INSERT INTO MEDICINE VALUES(NEWID(), 'Non-opioid analgesics', 'en','FS', '1');
INSERT INTO MEDICINE VALUES(NEWID(), 'Norethisterone acetate', 'en','FS', '1');
INSERT INTO MEDICINE VALUES(NEWID(), 'NSAID', 'en','FS', '1');
INSERT INTO MEDICINE VALUES(NEWID(), 'Nucleoside reverse transcriptase inhibitor', 'en','FS', '1');
INSERT INTO MEDICINE VALUES(NEWID(), 'Nystatin', 'en','FS', '1');
INSERT INTO MEDICINE VALUES(NEWID(), 'Oral contraceptives', 'en','FS', '1');
INSERT INTO MEDICINE VALUES(NEWID(), 'Oral polio vaccine', 'en','FS', '1');
INSERT INTO MEDICINE VALUES(NEWID(), 'Oral rehydration solution (ORS)', 'en','FS', '1');
INSERT INTO MEDICINE VALUES(NEWID(), 'Orphenadrine', 'en','FS', '1');
INSERT INTO MEDICINE VALUES(NEWID(), 'Oxygen', 'en','FS', '1');
INSERT INTO MEDICINE VALUES(NEWID(), 'Oxymetazoline, nasal', 'en','FS', '1');
INSERT INTO MEDICINE VALUES(NEWID(), 'Oxymetazoline, opthalmic', 'en','FS', '1');
INSERT INTO MEDICINE VALUES(NEWID(), 'Oxytocin', 'en','FS', '1');
INSERT INTO MEDICINE VALUES(NEWID(), 'Oxytocin/ergometrine', 'en','FS', '1');
INSERT INTO MEDICINE VALUES(NEWID(), 'Paracetamol', 'en','FS', '1');
INSERT INTO MEDICINE VALUES(NEWID(), 'Paraffin gauze dressings', 'en','FS', '1');
INSERT INTO MEDICINE VALUES(NEWID(), 'Permethrin', 'en','FS', '1');
INSERT INTO MEDICINE VALUES(NEWID(), 'Pethidine', 'en','FS', '1');
INSERT INTO MEDICINE VALUES(NEWID(), 'Petroleum Jelly', 'en','FS', '1');
INSERT INTO MEDICINE VALUES(NEWID(), 'Phenobarbital', 'en','FS', '1');
INSERT INTO MEDICINE VALUES(NEWID(), 'Phenoxymethylpenicillin', 'en','FS', '1');
INSERT INTO MEDICINE VALUES(NEWID(), 'Phenytoin', 'en','FS', '1');
INSERT INTO MEDICINE VALUES(NEWID(), 'Pneumococcal conjugated vaccine','en', 'FS', '1');
INSERT INTO MEDICINE VALUES(NEWID(), 'Potassium', 'en','FS', '1');
INSERT INTO MEDICINE VALUES(NEWID(), 'Povidone iodine, topical', 'en','FS', '1');
INSERT INTO MEDICINE VALUES(NEWID(), 'Povidone iodine, solution', 'en','FS', '1');
INSERT INTO MEDICINE VALUES(NEWID(), 'Praziquantel', 'en','FS', '1');
INSERT INTO MEDICINE VALUES(NEWID(), 'Prednisone (Prednisilone)', 'en','FS', '1');
INSERT INTO MEDICINE VALUES(NEWID(), 'Progestin-only injectable', 'en','FS', '1');
INSERT INTO MEDICINE VALUES(NEWID(), 'Progestin-only pills', 'en','FS', '1');
INSERT INTO MEDICINE VALUES(NEWID(), 'Progestin-only subdermal implant','en', 'FS', '1');
INSERT INTO MEDICINE VALUES(NEWID(), 'Progestin-only tablets','en', 'FS', '1');
INSERT INTO MEDICINE VALUES(NEWID(), 'Promethazine', 'en','FS', '1');
INSERT INTO MEDICINE VALUES(NEWID(), 'Protease inhibitor', 'en','FS', '1');
INSERT INTO MEDICINE VALUES(NEWID(), 'Proton-pump inhibitor', 'en','FS', '1');
INSERT INTO MEDICINE VALUES(NEWID(), 'Pyrazinamide', 'en','FS', '1');
INSERT INTO MEDICINE VALUES(NEWID(), 'Pyrazinamide, dispersible', 'en','FS', '1');
INSERT INTO MEDICINE VALUES(NEWID(), 'Pyridoxine', 'en','FS', '1');
INSERT INTO MEDICINE VALUES(NEWID(), 'Quinine dihydrochloride', 'en','FS', '1');
INSERT INTO MEDICINE VALUES(NEWID(), 'Rabies Immunoglobulin', 'en','FS', '1');
INSERT INTO MEDICINE VALUES(NEWID(), 'Rabies vaccine', 'en','FS', '1');
INSERT INTO MEDICINE VALUES(NEWID(), 'Rifampicin', 'en','FS', '1');
INSERT INTO MEDICINE VALUES(NEWID(), 'Rifampicin/Isoniazid', 'en','FS', '1');
INSERT INTO MEDICINE VALUES(NEWID(), 'Rifampicin/Isoniazid/Pyrazinamide/Ethambutol', 'en','FS', '1');
INSERT INTO MEDICINE VALUES(NEWID(), 'Risperidone', 'en','FS', '1');
INSERT INTO MEDICINE VALUES(NEWID(), 'Ritonavir', 'en','FS', '1');
INSERT INTO MEDICINE VALUES(NEWID(), 'Rotavirus vaccine', 'en','FS', '1');
INSERT INTO MEDICINE VALUES(NEWID(), 'Salbutamol, inhaler', 'en','FS', '1');
INSERT INTO MEDICINE VALUES(NEWID(), 'Salbutamol, parental', 'en','FS', '1');
INSERT INTO MEDICINE VALUES(NEWID(), 'Salbutamol, solution','en','FS', '1');
INSERT INTO MEDICINE VALUES(NEWID(), 'Salicylic Acid, topical', 'en','FS', '1');
INSERT INTO MEDICINE VALUES(NEWID(), 'Salmeterol/fluticasone, inhaler','en', 'FS', '1');
INSERT INTO MEDICINE VALUES(NEWID(), 'Selenium sulphide, topical','en', 'FS', '1');
INSERT INTO MEDICINE VALUES(NEWID(), 'Sennosides A and B','en', 'FS', '1');
INSERT INTO MEDICINE VALUES(NEWID(), 'Simvastatin', 'en','FS', '1');
INSERT INTO MEDICINE VALUES(NEWID(), 'Soap substitute', 'en','FS', '1');
INSERT INTO MEDICINE VALUES(NEWID(), 'Sodium Chloride 0.9%, parenteral','en', 'FS', '1');
INSERT INTO MEDICINE VALUES(NEWID(), 'Sodium Chloride 0.9%, nasal solution','en', 'FS', '1');
INSERT INTO MEDICINE VALUES(NEWID(), 'Sodium Chloride 0.9%, solution ', 'en','FS', '1');
INSERT INTO MEDICINE VALUES(NEWID(), 'Sodium Chloride 3-5%, solution', 'en','FS', '1');
INSERT INTO MEDICINE VALUES(NEWID(), 'Sodium Cromoglycate', 'en','FS', '1');
INSERT INTO MEDICINE VALUES(NEWID(), 'Spironolactone','en', 'FS', '1');
INSERT INTO MEDICINE VALUES(NEWID(), 'SSRI', 'en','FS', '1');
INSERT INTO MEDICINE VALUES(NEWID(), 'Stavudine', 'en','FS', '1');
INSERT INTO MEDICINE VALUES(NEWID(), 'Streptokinase', 'en','FS', '1');
INSERT INTO MEDICINE VALUES(NEWID(), 'Sulphonamides', 'en','FS', '1');
INSERT INTO MEDICINE VALUES(NEWID(), 'Sulphonylureas','en', 'FS', '1');
INSERT INTO MEDICINE VALUES(NEWID(), 'Tenofovir', 'en','FS', '1');
INSERT INTO MEDICINE VALUES(NEWID(), 'Terizidone', 'en','FS', '1');
INSERT INTO MEDICINE VALUES(NEWID(), 'Tetanus and diptheria vaccine', 'en','FS', '1');
INSERT INTO MEDICINE VALUES(NEWID(), 'Tetanus toxoid', 'en','FS', '1');
INSERT INTO MEDICINE VALUES(NEWID(), 'Tetracaine, opthalmic', 'en','FS', '1');
INSERT INTO MEDICINE VALUES(NEWID(), 'Tetracaine, topical', 'en','FS', '1');
INSERT INTO MEDICINE VALUES(NEWID(), 'Thiamine, oral', 'en','FS', '1');
INSERT INTO MEDICINE VALUES(NEWID(), 'Thiamine, parenteral', 'en','FS', '1');
INSERT INTO MEDICINE VALUES(NEWID(), 'Thiazide Diuretic', 'en','FS', '1');
INSERT INTO MEDICINE VALUES(NEWID(), 'Tincture of Iodine BP', 'en','FS', '1');
INSERT INTO MEDICINE VALUES(NEWID(), 'Topical Retinoids','en', 'FS', '1');
INSERT INTO MEDICINE VALUES(NEWID(), 'Tramadol', 'en','FS', '1');
INSERT INTO MEDICINE VALUES(NEWID(), 'Tretinoin', 'en','FS', '1');
INSERT INTO MEDICINE VALUES(NEWID(), 'Tricyclic antidepressants', 'en','FS', '1');
INSERT INTO MEDICINE VALUES(NEWID(), 'Triphasic: combined estrogen/progestin pills', 'en','FS', '1');
INSERT INTO MEDICINE VALUES(NEWID(), 'Valproate', 'en','FS', '1');
INSERT INTO MEDICINE VALUES(NEWID(), 'Vitamin A', 'en','FS', '1');
INSERT INTO MEDICINE VALUES(NEWID(), 'Vitamin B complex', 'en','FS', '1');
INSERT INTO MEDICINE VALUES(NEWID(), 'Vitamin K', 'en','FS', '1');
INSERT INTO MEDICINE VALUES(NEWID(), 'Water for injection', 'en','FS', '1');
INSERT INTO MEDICINE VALUES(NEWID(), 'Zidovudine', 'en','FS', '1');
INSERT INTO MEDICINE VALUES(NEWID(), 'Zinc, oral', 'en','FS', '1');
INSERT INTO MEDICINE VALUES(NEWID(), 'Zinc and caster oil ointment', 'en','FS', '1');
INSERT INTO MEDICINE VALUES(NEWID(), 'Zuclopenthixol acetate', 'en','FS', '1');
INSERT INTO MEDICINE VALUES(NEWID(), 'Zuclopenthixol decanoate', 'en','FS', '1');

INSERT INTO MEDICINE VALUES(NEWID(), 'acetato de betametasona + fosfato dissódico de betametasona', 'pt', 'BRA', '1');
INSERT INTO MEDICINE VALUES(NEWID(), 'acetato de hidrocortisona', 'pt', 'BRA', '1');
INSERT INTO MEDICINE VALUES(NEWID(), 'acetato de leuprorrelina', 'pt', 'BRA', '1');
INSERT INTO MEDICINE VALUES(NEWID(), 'acetato de medroxiprogesterona', 'pt', 'BRA', '1');
INSERT INTO MEDICINE VALUES(NEWID(), 'acetato de megestrol', 'pt', 'BRA', '1');
INSERT INTO MEDICINE VALUES(NEWID(), 'acetato de sódio', 'pt', 'BRA', '1');
INSERT INTO MEDICINE VALUES(NEWID(), 'acetazolamida', 'pt', 'BRA', '1');
INSERT INTO MEDICINE VALUES(NEWID(), 'aciclovir', 'pt', 'BRA', '1');
INSERT INTO MEDICINE VALUES(NEWID(), 'aciclovir sódico', 'pt', 'BRA', '1');
INSERT INTO MEDICINE VALUES(NEWID(), 'ácido acetilsalicílico', 'pt', 'BRA', '1');
INSERT INTO MEDICINE VALUES(NEWID(), 'ácido fólico', 'pt', 'BRA', '1');
INSERT INTO MEDICINE VALUES(NEWID(), 'ácido salicílico', 'pt', 'BRA', '1');
INSERT INTO MEDICINE VALUES(NEWID(), 'água para injeção', 'pt', 'BRA', '1');
INSERT INTO MEDICINE VALUES(NEWID(), 'albendazol', 'pt', 'BRA', '1');
INSERT INTO MEDICINE VALUES(NEWID(), 'albumina humana', 'pt', 'BRA', '1');
INSERT INTO MEDICINE VALUES(NEWID(), 'alcatrão mineral', 'pt', 'BRA', '1');
INSERT INTO MEDICINE VALUES(NEWID(), 'álcool etílico', 'pt', 'BRA', '1');
INSERT INTO MEDICINE VALUES(NEWID(), 'alendronato de sódio', 'pt', 'BRA', '1');
INSERT INTO MEDICINE VALUES(NEWID(), 'alfaporactanto', 'pt', 'BRA', '1');
INSERT INTO MEDICINE VALUES(NEWID(), 'alopurinol', 'pt', 'BRA', '1');
INSERT INTO MEDICINE VALUES(NEWID(), 'alteplase', 'pt', 'BRA', '1');
INSERT INTO MEDICINE VALUES(NEWID(), 'aminoácidos', 'pt', 'BRA', '1');
INSERT INTO MEDICINE VALUES(NEWID(), 'amoxicilina', 'pt', 'BRA', '1');
INSERT INTO MEDICINE VALUES(NEWID(), 'amoxicilina + clavulanato de potássio', 'pt', 'BRA', '1');
INSERT INTO MEDICINE VALUES(NEWID(), 'ampicilina sódica', 'pt', 'BRA', '1');
INSERT INTO MEDICINE VALUES(NEWID(), 'anastrozol', 'pt', 'BRA', '1');
INSERT INTO MEDICINE VALUES(NEWID(), 'anfotericina B', 'pt', 'BRA', '1');
INSERT INTO MEDICINE VALUES(NEWID(), 'antimoniato de meglumina', 'pt', 'BRA', '1');
INSERT INTO MEDICINE VALUES(NEWID(), 'arteméter', 'pt', 'BRA', '1');
INSERT INTO MEDICINE VALUES(NEWID(), 'artesunato de sódio', 'pt', 'BRA', '1');
INSERT INTO MEDICINE VALUES(NEWID(), 'artesunato de sódio + mefloquina', 'pt', 'BRA', '1');
INSERT INTO MEDICINE VALUES(NEWID(), 'asparaginase', 'pt', 'BRA', '1');
INSERT INTO MEDICINE VALUES(NEWID(), 'atenolol', 'pt', 'BRA', '1');
INSERT INTO MEDICINE VALUES(NEWID(), 'azatioprina', 'pt', 'BRA', '1');
INSERT INTO MEDICINE VALUES(NEWID(), 'azitromicina', 'pt', 'BRA', '1');
INSERT INTO MEDICINE VALUES(NEWID(), 'dacarbazina', 'pt', 'BRA', '1');
INSERT INTO MEDICINE VALUES(NEWID(), 'dactinomicina', 'pt', 'BRA', '1');
INSERT INTO MEDICINE VALUES(NEWID(), 'dalteparina sódica', 'pt', 'BRA', '1');
INSERT INTO MEDICINE VALUES(NEWID(), 'dapsona', 'pt', 'BRA', '1');
INSERT INTO MEDICINE VALUES(NEWID(), 'decanoato de haloperidol', 'pt', 'BRA', '1');
INSERT INTO MEDICINE VALUES(NEWID(), 'dexametasona', 'pt', 'BRA', '1');
INSERT INTO MEDICINE VALUES(NEWID(), 'diafragma', 'pt', 'BRA', '1');
INSERT INTO MEDICINE VALUES(NEWID(), 'diatrizoato de sódio + diatrizoato de meglumina', 'pt', 'BRA', '1');
INSERT INTO MEDICINE VALUES(NEWID(), 'diazepam ', 'pt', 'BRA', '1');
INSERT INTO MEDICINE VALUES(NEWID(), 'dicloridrato de quinina', 'pt', 'BRA', '1');
INSERT INTO MEDICINE VALUES(NEWID(), 'didanosina', 'pt', 'BRA', '1');
INSERT INTO MEDICINE VALUES(NEWID(), 'dietilcarbamazina', 'pt', 'BRA', '1');
INSERT INTO MEDICINE VALUES(NEWID(), 'difosfato de cloroquina', 'pt', 'BRA', '1');
INSERT INTO MEDICINE VALUES(NEWID(), 'difosfato de primaquina', 'pt', 'BRA', '1');
INSERT INTO MEDICINE VALUES(NEWID(), 'digoxina', 'pt', 'BRA', '1');
INSERT INTO MEDICINE VALUES(NEWID(), 'dinitrato de isossorbida', 'pt', 'BRA', '1');
INSERT INTO MEDICINE VALUES(NEWID(), 'dipirona sódica', 'pt', 'BRA', '1');
INSERT INTO MEDICINE VALUES(NEWID(), 'dipropionato de beclometasona', 'pt', 'BRA', '1');
INSERT INTO MEDICINE VALUES(NEWID(), 'dispositivo intrauterino plástico com cobre', 'pt', 'BRA', '1');
INSERT INTO MEDICINE VALUES(NEWID(), 'docetaxel', 'pt', 'BRA', '1');


CREATE TABLE PATIENT_USE_MEDICINE(
	id_patient_use_medicine CHAR(36) PRIMARY KEY,
	id_patient CHAR(36) NOT NULL,
	id_medicine CHAR(36) NOT NULL,
	CONSTRAINT FK_PATIENT_USE_MEDICINE_PATIENT FOREIGN KEY (id_patient) REFERENCES PATIENT(id_patient) ON DELETE CASCADE,
	CONSTRAINT FK_PATIENT_USE_MEDICINE_MEDICINE FOREIGN KEY (id_medicine) REFERENCES MEDICINE(id_medicine) ON DELETE CASCADE,
);


